import type { Creature } from '@/types/game'

export const CALIFORNIA_CREATURES: Creature[] = [
  // === DESERT BIOME ===
  {
    id: 'desert-tortoise',
    name: 'Desert Tortoise',
    scientificName: 'Gopherus agassizii',
    description: 'An ancient reptile of the Mojave. Spends 95% of its life in underground burrows.',
    lore: 'Desert tortoises can live 80+ years and survive a full year without water. Their burrows shelter over 350 other species. Listed as threatened since 1990, they face habitat loss from solar farms and off-road vehicles in the Mojave.',
    type: 'reptile',
    rarity: 'uncommon',
    biomes: ['desert', 'scrubland'],
    subregions: ['Mojave Desert', 'Joshua Tree', 'Death Valley', 'Anza-Borrego'],
    stats: { hp: 55, maxHp: 55, attack: 15, defense: 60, speed: 5 },
    isFantasy: false,
    sprite: '🐢',
    color: '#a8956e',
    activeTime: ['dawn', 'dusk'],
    moves: [
      { name: 'Shell Slam', power: 25, type: 'attack', description: 'Rams with armored shell' },
      { name: 'Burrow', power: 0, type: 'defend', description: 'Retreats into shell' },
      { name: 'Sand Kick', power: 15, type: 'special', description: 'Flings desert sand' },
    ],
  },
  {
    id: 'sidewinder',
    name: 'Sidewinder Rattlesnake',
    scientificName: 'Crotalus cerastes',
    description: 'A horned viper that moves sideways across hot sand, leaving distinctive J-shaped tracks.',
    lore: 'Sidewinders are perfectly adapted to desert life. Their unique locomotion keeps most of their body off the scorching sand. The horn-like scales above their eyes may shade them from the sun or prevent sand from covering their eyes during burial ambushes.',
    type: 'reptile',
    rarity: 'uncommon',
    biomes: ['desert', 'dunes'],
    subregions: ['Mojave Desert', 'Death Valley', 'Anza-Borrego'],
    stats: { hp: 35, maxHp: 35, attack: 45, defense: 20, speed: 38 },
    isFantasy: false,
    sprite: '🐍',
    color: '#d4a76a',
    activeTime: ['dusk', 'night'],
    moves: [
      { name: 'Venom Strike', power: 40, type: 'attack', description: 'Strikes with hemotoxic venom' },
      { name: 'Sidewind', power: 0, type: 'defend', description: 'Rapidly shifts across sand' },
      { name: 'Rattle Warning', power: 20, type: 'special', description: 'Intimidating rattle shake' },
    ],
  },
  {
    id: 'roadrunner',
    name: 'Greater Roadrunner',
    scientificName: 'Geococcyx californianus',
    description: 'A ground-dwelling cuckoo that prefers running to flying, reaching 20 mph on foot.',
    lore: 'Roadrunners are one of the few animals that prey on rattlesnakes. They work in pairs — one distracts while the other pecks the snake\'s head. They sunbathe by exposing dark skin patches on their back to absorb warmth on cold desert mornings.',
    type: 'bird',
    rarity: 'common',
    biomes: ['desert', 'scrubland', 'canyon'],
    subregions: ['Mojave Desert', 'Joshua Tree', 'Anza-Borrego', 'Inland Empire'],
    stats: { hp: 30, maxHp: 30, attack: 35, defense: 18, speed: 48 },
    isFantasy: false,
    sprite: '🐦',
    color: '#6b4423',
    activeTime: ['dawn', 'day'],
    moves: [
      { name: 'Sprint Strike', power: 30, type: 'attack', description: 'Charges at top speed' },
      { name: 'Dust Dodge', power: 0, type: 'defend', description: 'Zigzags to evade' },
      { name: 'Snake Snatch', power: 35, type: 'special', description: 'Grabs and shakes prey' },
    ],
  },
  {
    id: 'kit-fox',
    name: 'Kit Fox',
    scientificName: 'Vulpes macrotis',
    description: 'The smallest fox in North America, with enormous ears that dissipate heat and detect prey underground.',
    lore: 'The San Joaquin kit fox is listed as endangered. Their oversized ears are like natural satellite dishes, picking up the faintest rustle of a kangaroo rat underground. They dig complex burrow systems with multiple entrances for quick escape from coyotes.',
    type: 'beast',
    rarity: 'rare',
    biomes: ['desert', 'scrubland', 'valley'],
    subregions: ['Mojave Desert', 'Bakersfield', 'San Joaquin Valley', 'Carrizo Plain'],
    stats: { hp: 32, maxHp: 32, attack: 30, defense: 20, speed: 50 },
    isFantasy: false,
    sprite: '🦊',
    color: '#c4956a',
    activeTime: ['dusk', 'night'],
    moves: [
      { name: 'Pounce', power: 30, type: 'attack', description: 'Leaps on prey from above' },
      { name: 'Ear Scan', power: 0, type: 'defend', description: 'Listens for incoming threats' },
      { name: 'Burrow Escape', power: 15, type: 'special', description: 'Dives into an escape tunnel' },
    ],
  },
  {
    id: 'joshua-tree-spirit',
    name: 'Joshua Tree Spirit',
    scientificName: 'Spiritus yuccae',
    description: 'A glowing apparition that manifests around ancient Joshua trees under moonlight.',
    lore: 'Desert travelers have reported luminous figures near the oldest Joshua trees for centuries. Scientists dismiss them as heat shimmer or bioluminescent fungi, but rangers in the park know better. They appear only during the brief window of Joshua tree bloom.',
    type: 'mystic',
    rarity: 'rare',
    biomes: ['desert'],
    subregions: ['Joshua Tree'],
    stats: { hp: 40, maxHp: 40, attack: 40, defense: 35, speed: 30 },
    isFantasy: true,
    sprite: '🌵',
    color: '#7dd3a0',
    activeTime: ['night'],
    moves: [
      { name: 'Thorn Burst', power: 35, type: 'attack', description: 'Fires needle-sharp spines' },
      { name: 'Desert Mirage', power: 0, type: 'defend', description: 'Creates illusory copies' },
      { name: 'Moonbloom', power: 40, type: 'special', description: 'Channels lunar energy' },
    ],
  },
  {
    id: 'chuckwalla',
    name: 'Chuckwalla',
    scientificName: 'Sauromalus ater',
    description: 'A large desert lizard that inflates its body to wedge into rock crevices when threatened.',
    lore: 'Chuckwallas are strict herbivores, unusual for desert lizards. When threatened, they crawl into rock crevices and inflate their bodies so tightly they cannot be pulled out. Native Americans historically harvested them by deflating them with a pointed stick.',
    type: 'reptile',
    rarity: 'common',
    biomes: ['desert', 'canyon'],
    subregions: ['Joshua Tree', 'Death Valley', 'Anza-Borrego'],
    stats: { hp: 40, maxHp: 40, attack: 20, defense: 45, speed: 18 },
    isFantasy: false,
    sprite: '🦎',
    color: '#8b7355',
    activeTime: ['day'],
    moves: [
      { name: 'Tail Whip', power: 20, type: 'attack', description: 'Lashes with a thick tail' },
      { name: 'Inflate', power: 0, type: 'defend', description: 'Puffs up to wedge in place' },
      { name: 'Rock Slide', power: 25, type: 'special', description: 'Dislodges rocks onto foe' },
    ],
  },
  {
    id: 'death-valley-phantom',
    name: 'Death Valley Phantom',
    scientificName: 'Spectrum mortis',
    description: 'A shimmering heat mirage that takes on a life of its own in the lowest, hottest place on Earth.',
    lore: 'At 282 feet below sea level, Death Valley holds the record for the highest air temperature ever recorded: 134°F. Rangers report phantom figures dancing in the heat shimmer on the salt flats. Whether they are real or hallucination, no one who approaches has ever caught one.',
    type: 'mystic',
    rarity: 'legendary',
    biomes: ['desert'],
    subregions: ['Death Valley'],
    stats: { hp: 60, maxHp: 60, attack: 55, defense: 40, speed: 65 },
    isFantasy: true,
    sprite: '👻',
    color: '#fcd34d',
    activeTime: ['day'],
    moves: [
      { name: 'Heat Mirage', power: 45, type: 'special', description: 'Warps reality with extreme heat' },
      { name: 'Salt Burn', power: 35, type: 'attack', description: 'Corrosive salt crystal blast' },
      { name: 'Vanish', power: 0, type: 'defend', description: 'Dissolves into heat shimmer' },
    ],
  },
  // === ALPINE / SNOW BIOME ===
  {
    id: 'sierra-nevada-bighorn',
    name: 'Sierra Nevada Bighorn Sheep',
    scientificName: 'Ovis canadensis sierrae',
    description: 'A sure-footed climber of the highest Sierra peaks, with massive curled horns.',
    lore: 'Fewer than 600 Sierra Nevada bighorn sheep remain, making them one of the most endangered mammals in North America. They navigate near-vertical cliffs at elevations above 10,000 feet, escaping predators by retreating to terrain nothing else can traverse.',
    type: 'beast',
    rarity: 'rare',
    biomes: ['alpine', 'mountain'],
    subregions: ['Yosemite Valley', 'Mt. Whitney', 'Mammoth Lakes', 'Kings Canyon'],
    stats: { hp: 55, maxHp: 55, attack: 40, defense: 45, speed: 35 },
    isFantasy: false,
    sprite: '🐏',
    color: '#9ca3af',
    activeTime: ['dawn', 'day'],
    moves: [
      { name: 'Horn Charge', power: 40, type: 'attack', description: 'Rams with massive horns' },
      { name: 'Cliff Stance', power: 0, type: 'defend', description: 'Braces on steep terrain' },
      { name: 'Avalanche Kick', power: 35, type: 'special', description: 'Sends rocks tumbling down' },
    ],
  },
  {
    id: 'pika',
    name: 'American Pika',
    scientificName: 'Ochotona princeps',
    description: 'A tiny rabbit relative that lives in alpine rockslides, gathering haypiles for winter.',
    lore: 'Pikas are a bellwether of climate change — they die of overheating at just 78°F. As temperatures rise, they retreat upslope, but eventually there is nowhere higher to go. Their distinctive "eep!" calls echo across Sierra talus fields. They spend summer frantically gathering wildflowers to cure into haystacks for winter.',
    type: 'beast',
    rarity: 'uncommon',
    biomes: ['alpine', 'snow'],
    subregions: ['Yosemite Valley', 'Mt. Whitney', 'Mammoth Lakes', 'Lake Tahoe'],
    stats: { hp: 22, maxHp: 22, attack: 15, defense: 25, speed: 40 },
    isFantasy: false,
    sprite: '🐹',
    color: '#a1887f',
    activeTime: ['day'],
    moves: [
      { name: 'Quick Dash', power: 20, type: 'attack', description: 'Darts out from the rocks' },
      { name: 'Rock Hide', power: 0, type: 'defend', description: 'Vanishes into talus field' },
      { name: 'Alarm Call', power: 15, type: 'special', description: 'Piercing "eep!" startles foe' },
    ],
  },
  {
    id: 'clark-nutcracker',
    name: 'Clark\'s Nutcracker',
    scientificName: 'Nucifraga columbiana',
    description: 'A bold gray bird of the high Sierra that caches 30,000 pine seeds each fall — and remembers where it buried them.',
    lore: 'Clark\'s nutcrackers have a spatial memory that puts GPS to shame. Each bird buries up to 30,000 whitebark pine seeds in thousands of locations across miles of terrain, and retrieves them months later under feet of snow. The seeds they forget become the next generation of trees.',
    type: 'bird',
    rarity: 'common',
    biomes: ['alpine', 'mountain', 'snow'],
    subregions: ['Yosemite Valley', 'Lake Tahoe', 'Mammoth Lakes', 'Mt. Shasta'],
    stats: { hp: 30, maxHp: 30, attack: 28, defense: 22, speed: 38 },
    isFantasy: false,
    sprite: '🐦',
    color: '#78909c',
    activeTime: ['day'],
    moves: [
      { name: 'Seed Shot', power: 25, type: 'attack', description: 'Fires cached pine nuts' },
      { name: 'Memory Flash', power: 0, type: 'defend', description: 'Recalls hidden escape route' },
      { name: 'Wing Gust', power: 20, type: 'special', description: 'Buffets with alpine winds' },
    ],
  },
  {
    id: 'sierra-spirit',
    name: 'Sierra Spirit',
    scientificName: 'Animae alpinae',
    description: 'A luminous entity seen on moonlit nights above treeline, wreathed in glacial mist.',
    lore: 'Mountaineers have reported a glowing figure on the ridgeline between Half Dome and Clouds Rest since the 1870s. John Muir himself wrote of "pale fire walking the granite." Modern climbers say it appears before storms, perhaps some atmospheric phenomenon we don\'t yet understand.',
    type: 'mystic',
    rarity: 'legendary',
    biomes: ['alpine', 'snow'],
    subregions: ['Yosemite Valley', 'Mt. Whitney'],
    stats: { hp: 65, maxHp: 65, attack: 55, defense: 50, speed: 45 },
    isFantasy: true,
    sprite: '✨',
    color: '#93c5fd',
    activeTime: ['night'],
    moves: [
      { name: 'Glacier Pulse', power: 50, type: 'special', description: 'Wave of ancient ice energy' },
      { name: 'Alpine Gale', power: 40, type: 'attack', description: 'Howling mountain wind blast' },
      { name: 'Granite Shield', power: 0, type: 'defend', description: 'Encases in living rock' },
    ],
  },
  // === VALLEY BIOME ===
  {
    id: 'burrowing-owl',
    name: 'Burrowing Owl',
    scientificName: 'Athene cunicularia',
    description: 'A tiny owl that lives in ground squirrel burrows in the Central Valley grasslands.',
    lore: 'Unlike most owls, burrowing owls are active during the day. They line their burrow entrances with cow dung to attract dung beetles for food. When threatened, juveniles make a rattlesnake-like buzzing sound from inside the burrow to deter predators.',
    type: 'bird',
    rarity: 'uncommon',
    biomes: ['valley', 'grassland'],
    subregions: ['Davis', 'Bakersfield', 'Fresno', 'San Joaquin Valley', 'Stockton'],
    stats: { hp: 28, maxHp: 28, attack: 30, defense: 18, speed: 35 },
    isFantasy: false,
    sprite: '🦉',
    color: '#a0845c',
    activeTime: ['day', 'dusk'],
    moves: [
      { name: 'Ground Dive', power: 28, type: 'attack', description: 'Swoops low along the ground' },
      { name: 'Burrow Retreat', power: 0, type: 'defend', description: 'Ducks into underground nest' },
      { name: 'Mimicry Buzz', power: 20, type: 'special', description: 'Imitates a rattlesnake' },
    ],
  },
  {
    id: 'valley-elderberry-beetle',
    name: 'Valley Elderberry Beetle',
    scientificName: 'Desmocerus californicus dimorphus',
    description: 'A threatened metallic-green longhorn beetle tied to Central Valley elderberry bushes.',
    lore: 'This beetle spends most of its 2-year life as a larva inside elderberry stems. Adults emerge for just a few weeks to mate. Its dependence on riparian elderberry habitat makes it a canary in the coal mine for Central Valley ecosystem health.',
    type: 'insect',
    rarity: 'rare',
    biomes: ['valley'],
    subregions: ['Sacramento', 'Stockton', 'San Joaquin Valley'],
    stats: { hp: 18, maxHp: 18, attack: 22, defense: 30, speed: 20 },
    isFantasy: false,
    sprite: '🪲',
    color: '#22c55e',
    activeTime: ['day'],
    moves: [
      { name: 'Mandible Bite', power: 25, type: 'attack', description: 'Pinches with strong jaws' },
      { name: 'Shell Guard', power: 0, type: 'defend', description: 'Pulls legs under hard wing covers' },
      { name: 'Pollen Burst', power: 20, type: 'special', description: 'Shakes off blinding pollen' },
    ],
  },
  {
    id: 'tricolored-blackbird',
    name: 'Tricolored Blackbird',
    scientificName: 'Agelaius tricolor',
    description: 'A colonial nesting bird found almost exclusively in California, forming massive breeding colonies.',
    lore: 'Tricolored blackbirds form the largest breeding colonies of any North American land bird — up to 100,000 nests in a single marsh. Despite this, their population has crashed 90% since the 1930s. Nearly the entire species lives in California\'s Central Valley.',
    type: 'bird',
    rarity: 'uncommon',
    biomes: ['valley', 'marsh'],
    subregions: ['Sacramento', 'San Joaquin Valley', 'Merced', 'Fresno'],
    stats: { hp: 22, maxHp: 22, attack: 25, defense: 15, speed: 40 },
    isFantasy: false,
    sprite: '🐦‍⬛',
    color: '#1f2937',
    activeTime: ['dawn', 'day'],
    moves: [
      { name: 'Flock Strike', power: 30, type: 'attack', description: 'Calls in the colony to mob' },
      { name: 'Reed Hide', power: 0, type: 'defend', description: 'Disappears into marsh reeds' },
      { name: 'Colony Call', power: 20, type: 'special', description: 'Deafening chorus of thousands' },
    ],
  },
  // === VOLCANIC BIOME ===
  {
    id: 'lava-beetle',
    name: 'Lava Tube Beetle',
    scientificName: 'Glacicavicola bathyscioides',
    description: 'A blind, heat-adapted beetle found in the lava tubes of the Cascade Range.',
    lore: 'These tiny beetles have evolved in total darkness inside lava tubes at Lava Beds National Monument. They have no eyes, no wings, and no pigment. They navigate by sensing vibrations in the volcanic rock and feed on organic material washed in by rare floods.',
    type: 'insect',
    rarity: 'rare',
    biomes: ['volcanic'],
    subregions: ['Lava Beds', 'Mt. Shasta', 'Lassen Volcanic'],
    stats: { hp: 25, maxHp: 25, attack: 20, defense: 40, speed: 12 },
    isFantasy: false,
    sprite: '🪲',
    color: '#4a3728',
    activeTime: ['night', 'day'],
    moves: [
      { name: 'Obsidian Bite', power: 25, type: 'attack', description: 'Jaws hardened by volcanic minerals' },
      { name: 'Cave Camouflage', power: 0, type: 'defend', description: 'Blends with lava rock' },
      { name: 'Tremor Sense', power: 20, type: 'special', description: 'Detects foe through ground vibration' },
    ],
  },
  {
    id: 'cascades-fire-spirit',
    name: 'Cascades Fire Spirit',
    scientificName: 'Ignis cascadiae',
    description: 'A smoldering entity that haunts the fumaroles and hot springs of volcanic peaks.',
    lore: 'When Lassen Peak erupted in 1915, hikers reported seeing a glowing figure walking through the pyroclastic flow unharmed. Similar sightings near Mt. Shasta\'s fumaroles continue today. Geologists chalk it up to superheated gas venting, but local tribes have older stories.',
    type: 'mystic',
    rarity: 'rare',
    biomes: ['volcanic', 'mountain'],
    subregions: ['Lassen Volcanic', 'Mt. Shasta'],
    stats: { hp: 45, maxHp: 45, attack: 50, defense: 30, speed: 35 },
    isFantasy: true,
    sprite: '🔥',
    color: '#ef4444',
    activeTime: ['dusk', 'night'],
    moves: [
      { name: 'Magma Burst', power: 45, type: 'attack', description: 'Erupts with molten rock' },
      { name: 'Sulfur Cloud', power: 0, type: 'defend', description: 'Shrouds self in toxic gas' },
      { name: 'Pyroclastic Roar', power: 40, type: 'special', description: 'Superheated shockwave' },
    ],
  },
  // === CANYON BIOME ===
  {
    id: 'canyon-wren',
    name: 'Canyon Wren',
    scientificName: 'Catherpes mexicanus',
    description: 'A small bird whose cascading song echoes through narrow canyon walls.',
    lore: 'The canyon wren\'s descending song is one of the most beautiful sounds in western canyons. They creep along vertical rock faces like feathered spiders, probing crevices with their long curved bills for insects. Their flat skulls allow them to peer into cracks nothing else can reach.',
    type: 'bird',
    rarity: 'common',
    biomes: ['canyon', 'mountain'],
    subregions: ['Kings Canyon', 'Yosemite Valley', 'Anza-Borrego', 'Big Sur'],
    stats: { hp: 20, maxHp: 20, attack: 22, defense: 15, speed: 42 },
    isFantasy: false,
    sprite: '🐦',
    color: '#b45309',
    activeTime: ['dawn', 'day'],
    moves: [
      { name: 'Echo Song', power: 25, type: 'special', description: 'Cascading notes disorient foe' },
      { name: 'Cliff Creep', power: 0, type: 'defend', description: 'Flattens against rock face' },
      { name: 'Crevice Probe', power: 20, type: 'attack', description: 'Jabs with long curved bill' },
    ],
  },
  {
    id: 'ringtail',
    name: 'Ringtail',
    scientificName: 'Bassariscus astutus',
    description: 'A nocturnal relative of the raccoon with enormous eyes and a long banded tail.',
    lore: 'Ringtails are California\'s state mammal (since 2024) yet most Californians have never seen one. They are fantastic climbers — their hind feet rotate 180° so they can descend headfirst. Gold Rush miners kept them as mousers, earning them the nickname "miner\'s cat."',
    type: 'beast',
    rarity: 'uncommon',
    biomes: ['canyon', 'forest', 'scrubland'],
    subregions: ['Kings Canyon', 'Yosemite Valley', 'Big Sur', 'Mt. Diablo'],
    stats: { hp: 30, maxHp: 30, attack: 28, defense: 22, speed: 45 },
    isFantasy: false,
    sprite: '🦝',
    color: '#78716c',
    activeTime: ['night'],
    moves: [
      { name: 'Night Pounce', power: 30, type: 'attack', description: 'Leaps from darkness' },
      { name: 'Wall Run', power: 0, type: 'defend', description: 'Scurries up a vertical surface' },
      { name: 'Tail Flash', power: 20, type: 'special', description: 'Distracts with banded tail' },
    ],
  },
  // === LAKESHORE BIOME ===
  {
    id: 'osprey',
    name: 'Osprey',
    scientificName: 'Pandion haliaetus',
    description: 'A fishing hawk that dives feet-first into lakes, catching fish with reversible outer toes.',
    lore: 'Ospreys are the only raptor in North America whose diet is almost exclusively live fish. They can dive from 100 feet, submerge completely, and take off from the water carrying a fish that weighs half their body weight. Their feet have barbed pads for gripping slippery prey.',
    type: 'bird',
    rarity: 'uncommon',
    biomes: ['lakeshore', 'water'],
    subregions: ['Lake Tahoe', 'Shasta Lake', 'Clear Lake', 'Folsom Lake', 'Mono Lake'],
    stats: { hp: 38, maxHp: 38, attack: 40, defense: 22, speed: 44 },
    isFantasy: false,
    sprite: '🦅',
    color: '#4a3728',
    activeTime: ['dawn', 'day'],
    moves: [
      { name: 'Plunge Dive', power: 38, type: 'attack', description: 'Dives talons-first from height' },
      { name: 'Hover', power: 0, type: 'defend', description: 'Kites on the wind' },
      { name: 'Fish Toss', power: 25, type: 'special', description: 'Flings a slippery fish' },
    ],
  },
  {
    id: 'tahoe-stonefly',
    name: 'Tahoe Stonefly',
    scientificName: 'Capnia lacustra',
    description: 'A flightless stonefly found only on the floor of Lake Tahoe — one of the rarest insects on Earth.',
    lore: 'The Tahoe stonefly is found nowhere else in the world. It lives at depths of 60-200 feet in Lake Tahoe\'s frigid, crystal-clear water. Listed as endangered, it is threatened by declining water clarity. It breathes through gills and never leaves the lake bottom.',
    type: 'insect',
    rarity: 'rare',
    biomes: ['lakeshore'],
    subregions: ['Lake Tahoe'],
    stats: { hp: 15, maxHp: 15, attack: 10, defense: 35, speed: 8 },
    isFantasy: false,
    sprite: '🪰',
    color: '#6b7280',
    activeTime: ['night', 'dawn'],
    moves: [
      { name: 'Gill Pulse', power: 15, type: 'special', description: 'Sends a water-pressure wave' },
      { name: 'Deep Dive', power: 0, type: 'defend', description: 'Retreats to the lake floor' },
      { name: 'Mineral Bite', power: 20, type: 'attack', description: 'Mandibles tough as granite' },
    ],
  },
  {
    id: 'mono-brine-shrimp',
    name: 'Mono Brine Shrimp',
    scientificName: 'Artemia monica',
    description: 'A tiny crustacean found only in the hypersaline waters of Mono Lake.',
    lore: 'Mono brine shrimp exist nowhere else on Earth. Four trillion of them populate Mono Lake, turning the alkaline waters green with their feeding. They are the sole food source for the millions of migratory birds that stop at Mono Lake — it is one of the most critical bird habitats in the West.',
    type: 'marine',
    rarity: 'common',
    biomes: ['lakeshore'],
    subregions: ['Mono Lake'],
    stats: { hp: 10, maxHp: 10, attack: 8, defense: 12, speed: 25 },
    isFantasy: false,
    sprite: '🦐',
    color: '#f97316',
    activeTime: ['day'],
    moves: [
      { name: 'Brine Spray', power: 15, type: 'attack', description: 'Jets alkaline water' },
      { name: 'Swarm Shield', power: 0, type: 'defend', description: 'Hides among trillions of kin' },
      { name: 'Salt Sting', power: 18, type: 'special', description: 'Concentrated salt burn' },
    ],
  },
  // === OLD GROWTH BIOME ===
  {
    id: 'marbled-murrelet',
    name: 'Marbled Murrelet',
    scientificName: 'Brachyramphus marmoratus',
    description: 'A small seabird that nests on mossy branches 200 feet up in old-growth redwoods — miles from the ocean.',
    lore: 'For decades, no one knew where marbled murrelets nested. In 1974, a tree surgeon found the first nest — on a mossy old-growth limb high in the redwoods. They fly to the ocean each dawn and return at dusk, commuting up to 50 miles each way. Only ancient, moss-draped branches will do.',
    type: 'bird',
    rarity: 'rare',
    biomes: ['old_growth', 'redwood'],
    subregions: ['Muir Woods', 'Big Basin', 'Prairie Creek Redwoods', 'Humboldt Redwoods'],
    stats: { hp: 25, maxHp: 25, attack: 22, defense: 18, speed: 48 },
    isFantasy: false,
    sprite: '🐦',
    color: '#4b5563',
    activeTime: ['dawn', 'dusk'],
    moves: [
      { name: 'Dive Bomb', power: 30, type: 'attack', description: 'Plummets from the canopy' },
      { name: 'Moss Cloak', power: 0, type: 'defend', description: 'Vanishes into lichen-covered branch' },
      { name: 'Sea Mist', power: 20, type: 'special', description: 'Conjures coastal fog' },
    ],
  },
  {
    id: 'northern-spotted-owl',
    name: 'Northern Spotted Owl',
    scientificName: 'Strix occidentalis caurina',
    description: 'An elusive old-growth specialist that requires vast tracts of ancient forest to survive.',
    lore: 'The northern spotted owl became the symbol of the Pacific Northwest timber wars of the 1990s. It needs 2,000+ acres of old-growth forest per pair. Population has declined 75% since the 1990s as barred owls invade from the east, outcompeting them for territory.',
    type: 'bird',
    rarity: 'rare',
    biomes: ['old_growth', 'redwood', 'forest'],
    subregions: ['Prairie Creek Redwoods', 'Humboldt Redwoods', 'Muir Woods'],
    stats: { hp: 35, maxHp: 35, attack: 35, defense: 28, speed: 32 },
    isFantasy: false,
    sprite: '🦉',
    color: '#6b4423',
    activeTime: ['night', 'dusk'],
    moves: [
      { name: 'Silent Strike', power: 35, type: 'attack', description: 'Swoops without a sound' },
      { name: 'Old Growth Fade', power: 0, type: 'defend', description: 'Melts into dark canopy' },
      { name: 'Hoot Tremor', power: 25, type: 'special', description: 'Deep hoots shake the air' },
    ],
  },
  // === SCRUBLAND BIOME ===
  {
    id: 'california-quail',
    name: 'California Quail',
    scientificName: 'Callipepla californica',
    description: 'California\'s state bird, with a jaunty topknot plume bobbing as it runs through chaparral.',
    lore: 'California quail are almost always in coveys of 10-200 birds. They roost in dense shrubs and post sentinels while the group feeds. Their "chi-CA-go" call is the soundtrack of California\'s golden hills. The male\'s teardrop-shaped head plume is one of the most recognized bird features in the state.',
    type: 'bird',
    rarity: 'common',
    biomes: ['scrubland', 'grassland', 'canyon'],
    subregions: ['Marin Headlands', 'Rancho San Antonio', 'Carrizo Plain', 'Mt. Diablo', 'Anza-Borrego'],
    stats: { hp: 22, maxHp: 22, attack: 18, defense: 15, speed: 38 },
    isFantasy: false,
    sprite: '🐦',
    color: '#6b7280',
    activeTime: ['dawn', 'day'],
    moves: [
      { name: 'Covey Rush', power: 25, type: 'attack', description: 'Entire flock charges at once' },
      { name: 'Scrub Dive', power: 0, type: 'defend', description: 'Disappears into dense brush' },
      { name: 'Alarm Call', power: 18, type: 'special', description: 'Sharp "pip-pip" warns the flock' },
    ],
  },
  {
    id: 'horned-lizard',
    name: 'Coast Horned Lizard',
    scientificName: 'Phrynosoma blainvillii',
    description: 'A flat, spiny lizard that can shoot blood from its eyes to deter predators.',
    lore: 'Horned lizards are one of the strangest reptiles in California. When grabbed by a predator, they increase blood pressure in their head until blood jets from the corners of their eyes — up to 5 feet. The blood tastes foul to canine and feline predators. They are an ant specialist, eating up to 100 harvester ants per day.',
    type: 'reptile',
    rarity: 'uncommon',
    biomes: ['scrubland', 'desert', 'grassland'],
    subregions: ['Anza-Borrego', 'Carrizo Plain', 'Joshua Tree', 'Inland Empire'],
    stats: { hp: 28, maxHp: 28, attack: 22, defense: 38, speed: 15 },
    isFantasy: false,
    sprite: '🦎',
    color: '#a16207',
    activeTime: ['day'],
    moves: [
      { name: 'Blood Squirt', power: 30, type: 'special', description: 'Shoots blood from eyes' },
      { name: 'Spike Defense', power: 0, type: 'defend', description: 'Puffs up to bristle spines' },
      { name: 'Ant Snap', power: 18, type: 'attack', description: 'Lightning-fast tongue strike' },
    ],
  },
  // === DUNES BIOME ===
  {
    id: 'snowy-plover',
    name: 'Western Snowy Plover',
    scientificName: 'Charadrius nivosus',
    description: 'A tiny shorebird that nests directly on sand dunes, perfectly camouflaged.',
    lore: 'Snowy plovers scrape shallow nests right on the beach. Their eggs look like sand grains. Fewer than 2,500 breed along the California coast, threatened by beachgoers and unleashed dogs. Entire sections of popular beaches are fenced off each spring to protect their nests.',
    type: 'bird',
    rarity: 'uncommon',
    biomes: ['dunes', 'beach'],
    subregions: ['Monterey Bay', 'Half Moon Bay', 'Point Reyes', 'Santa Barbara', 'Pismo Beach'],
    stats: { hp: 18, maxHp: 18, attack: 12, defense: 15, speed: 45 },
    isFantasy: false,
    sprite: '🐦',
    color: '#e5e7eb',
    activeTime: ['dawn', 'day'],
    moves: [
      { name: 'Broken Wing', power: 0, type: 'defend', description: 'Fakes injury to lure foe away' },
      { name: 'Sand Sprint', power: 18, type: 'attack', description: 'Dashes across open sand' },
      { name: 'Dune Gust', power: 20, type: 'special', description: 'Wind kicks up blinding sand' },
    ],
  },
  {
    id: 'dune-beetle',
    name: 'Globose Dune Beetle',
    scientificName: 'Coelus globosus',
    description: 'A small flightless beetle found only in California coastal dunes, threatened by development.',
    lore: 'Globose dune beetles have lost the ability to fly — their wing covers are fused shut. They burrow into sand at the base of dune plants, emerging at night to feed on organic detritus. Listed as endangered by California, they survive on fewer than a dozen dune systems.',
    type: 'insect',
    rarity: 'rare',
    biomes: ['dunes'],
    subregions: ['Half Moon Bay', 'Monterey Bay', 'Pismo Beach'],
    stats: { hp: 15, maxHp: 15, attack: 12, defense: 42, speed: 8 },
    isFantasy: false,
    sprite: '🪲',
    color: '#1f2937',
    activeTime: ['night'],
    moves: [
      { name: 'Sand Burrow', power: 0, type: 'defend', description: 'Digs rapidly into sand' },
      { name: 'Shell Charge', power: 20, type: 'attack', description: 'Rams with armored body' },
      { name: 'Dune Shift', power: 15, type: 'special', description: 'Destabilizes the sand underfoot' },
    ],
  },
  // === SOCAL / CHAPARRAL / ADDITIONAL REGIONS ===
  {
    id: 'island-fox',
    name: 'Channel Island Fox',
    scientificName: 'Urocyon littoralis',
    description: 'A miniature fox found only on the Channel Islands, the size of a housecat.',
    lore: 'Channel Island foxes are the smallest canid in North America. Each island has its own subspecies, distinct after 10,000+ years of isolation. They nearly went extinct in the late 1990s when golden eagles colonized the islands and began preying on them. A heroic recovery program brought them back from fewer than 100 individuals.',
    type: 'beast',
    rarity: 'rare',
    biomes: ['scrubland', 'grassland'],
    subregions: ['Santa Cruz Island', 'Santa Catalina Island'],
    stats: { hp: 28, maxHp: 28, attack: 25, defense: 18, speed: 42 },
    isFantasy: false,
    sprite: '🦊',
    color: '#9ca3af',
    activeTime: ['dusk', 'night'],
    moves: [
      { name: 'Island Pounce', power: 28, type: 'attack', description: 'Leaps from island scrub' },
      { name: 'Miniature Dodge', power: 0, type: 'defend', description: 'Too small to hit' },
      { name: 'Coastal Bark', power: 18, type: 'special', description: 'Sharp yips echo off cliffs' },
    ],
  },
  {
    id: 'california-gnatcatcher',
    name: 'California Gnatcatcher',
    scientificName: 'Polioptila californica',
    description: 'A tiny songbird of coastal sage scrub, one of the most endangered habitats in North America.',
    lore: 'This little gray bird sparked one of the biggest environmental fights in California history. Its listing as threatened in 1993 halted billions of dollars of development in Southern California. Only 3,000 pairs remain, all in a narrow strip of coastal sage scrub between LA and San Diego.',
    type: 'bird',
    rarity: 'rare',
    biomes: ['scrubland'],
    subregions: ['San Diego', 'Orange County', 'Inland Empire'],
    stats: { hp: 16, maxHp: 16, attack: 18, defense: 12, speed: 44 },
    isFantasy: false,
    sprite: '🐦',
    color: '#6b7280',
    activeTime: ['dawn', 'day'],
    moves: [
      { name: 'Buzz Call', power: 20, type: 'special', description: 'Mewing cat-like call startles' },
      { name: 'Sage Flit', power: 0, type: 'defend', description: 'Darts through dense scrub' },
      { name: 'Gnat Snatch', power: 22, type: 'attack', description: 'Quick bill snap' },
    ],
  },
  {
    id: 'tarantula-hawk',
    name: 'Tarantula Hawk Wasp',
    scientificName: 'Pepsis grossa',
    description: 'A massive blue-black wasp that hunts tarantulas — its sting is one of the most painful of any insect.',
    lore: 'The tarantula hawk has the second most painful sting of any insect, described as "like being electrocuted in a bathtub." Despite this, they are docile toward humans. Females paralyze tarantulas and lay a single egg on the living spider. The larva eats the tarantula alive over weeks, saving vital organs for last.',
    type: 'insect',
    rarity: 'uncommon',
    biomes: ['desert', 'scrubland', 'canyon'],
    subregions: ['Anza-Borrego', 'Joshua Tree', 'Inland Empire', 'Mojave Desert'],
    stats: { hp: 30, maxHp: 30, attack: 48, defense: 15, speed: 40 },
    isFantasy: false,
    sprite: '🐝',
    color: '#1e40af',
    activeTime: ['day'],
    moves: [
      { name: 'Paralysis Sting', power: 45, type: 'attack', description: 'Venom paralyzes prey' },
      { name: 'Wing Buzz', power: 0, type: 'defend', description: 'Intimidating wing vibration' },
      { name: 'Hawk Dive', power: 30, type: 'special', description: 'Swoops like its namesake' },
    ],
  },
  // === NORTHERN CALIFORNIA / CASCADES ===
  {
    id: 'black-bear',
    name: 'California Black Bear',
    scientificName: 'Ursus americanus californiensis',
    description: 'The largest predator in California, roaming forests from Shasta to the Sierra.',
    lore: 'Despite the grizzly on the state flag, California\'s grizzlies have been extinct since 1924. Black bears remain, about 30,000 strong. Some Yosemite bears have learned to identify cooler brands by logo — rangers have documented them ignoring generic coolers to break into the good ones.',
    type: 'beast',
    rarity: 'uncommon',
    biomes: ['forest', 'mountain', 'old_growth'],
    subregions: ['Yosemite Valley', 'Lake Tahoe', 'Mt. Shasta', 'Sequoia National Park', 'Big Sur'],
    stats: { hp: 65, maxHp: 65, attack: 45, defense: 40, speed: 30 },
    isFantasy: false,
    sprite: '🐻',
    color: '#1f2937',
    activeTime: ['dawn', 'dusk', 'night'],
    moves: [
      { name: 'Bear Swipe', power: 40, type: 'attack', description: 'Powerful clawed strike' },
      { name: 'Thick Hide', power: 0, type: 'defend', description: 'Absorbs blows with bulk' },
      { name: 'Roar', power: 30, type: 'special', description: 'Terrifying growl' },
    ],
  },
  {
    id: 'wolverine',
    name: 'Sierra Wolverine',
    scientificName: 'Gulo gulo',
    description: 'An incredibly rare mustelid spotted in the Sierra Nevada for the first time in nearly a century.',
    lore: 'In 2008, a single wolverine was confirmed in the Tahoe National Forest — the first documented in California since 1922. It likely walked from Idaho or Montana. Wolverines are ferocious fighters that can drive bears and mountain lions off kills. A confirmed breeding population in California would be a conservation miracle.',
    type: 'beast',
    rarity: 'legendary',
    biomes: ['alpine', 'snow', 'mountain'],
    subregions: ['Lake Tahoe', 'Mt. Shasta', 'Mammoth Lakes'],
    stats: { hp: 50, maxHp: 50, attack: 60, defense: 45, speed: 40 },
    isFantasy: false,
    sprite: '🦡',
    color: '#4a3728',
    activeTime: ['dawn', 'dusk', 'night'],
    moves: [
      { name: 'Berserker Bite', power: 50, type: 'attack', description: 'Locks jaws and shakes' },
      { name: 'Snow Tunnel', power: 0, type: 'defend', description: 'Burrows under snowpack' },
      { name: 'Musk Spray', power: 30, type: 'special', description: 'Overpowering stench' },
    ],
  },
  // === MORE STATEWIDE SPECIES ===
  {
    id: 'california-condor-socal',
    name: 'California Condor (SoCal)',
    scientificName: 'Gymnogyps californianus',
    description: 'A massive vulture with a 9.5-foot wingspan, soaring over the canyons of Southern California.',
    lore: 'With only 22 birds left in 1982, every condor was captured for breeding. Today over 300 fly free. The SoCal population nests in the Transverse Ranges near Pinnacles and the Ventana Wilderness. They can soar for hours without flapping, riding thermals at 15,000 feet.',
    type: 'bird',
    rarity: 'legendary',
    biomes: ['canyon', 'mountain', 'scrubland'],
    subregions: ['Big Sur', 'Pinnacles', 'Santa Barbara', 'Ventura'],
    stats: { hp: 60, maxHp: 60, attack: 35, defense: 40, speed: 42 },
    isFantasy: false,
    sprite: '🦅',
    color: '#1f2937',
    activeTime: ['day'],
    conservationStatus: 'CR' as const,
    moves: [
      { name: 'Thermal Soar', power: 35, type: 'attack', description: 'Dive from extreme height' },
      { name: 'Wingspan Block', power: 0, type: 'defend', description: '9.5-foot wings shield body' },
      { name: 'Ancient Cry', power: 40, type: 'special', description: 'A sound from the Pleistocene' },
    ],
  },
  {
    id: 'coho-salmon',
    name: 'Coho Salmon',
    scientificName: 'Oncorhynchus kisutch',
    description: 'A silver-sided salmon that returns to its birth stream to spawn, turning brilliant red.',
    lore: 'Central California coho salmon are critically endangered. They navigate thousands of miles of ocean then find their way back to the exact creek where they hatched, using Earth\'s magnetic field and their sense of smell. They die after spawning, their bodies feeding the forest that shelters the next generation.',
    type: 'marine',
    rarity: 'rare',
    biomes: ['water', 'forest'],
    subregions: ['Point Reyes', 'Big Sur', 'Humboldt Bay', 'Prairie Creek Redwoods'],
    stats: { hp: 35, maxHp: 35, attack: 28, defense: 20, speed: 42 },
    isFantasy: false,
    sprite: '🐟',
    color: '#dc2626',
    activeTime: ['dawn', 'day'],
    conservationStatus: 'EN' as const,
    moves: [
      { name: 'Upstream Charge', power: 35, type: 'attack', description: 'Powers against the current' },
      { name: 'Leap', power: 0, type: 'defend', description: 'Jumps clear of the water' },
      { name: 'Spawn Surge', power: 30, type: 'special', description: 'Final burst of life energy' },
    ],
  },
  {
    id: 'elephant-seal',
    name: 'Northern Elephant Seal',
    scientificName: 'Mirounga angustirostris',
    description: 'A massive marine mammal — bulls weigh up to 5,000 lbs and have an inflatable snout.',
    lore: 'Hunted to near-extinction by 1892 (only 20-100 remained), elephant seals have rebounded to 175,000 thanks to protection. Bulls battle ferociously on the beaches at Año Nuevo and Piedras Blancas. They dive deeper than 5,000 feet — deeper than most submarines — and hold their breath for up to 2 hours.',
    type: 'marine',
    rarity: 'uncommon',
    biomes: ['beach', 'rocky_beach'],
    subregions: ['Big Sur', 'Point Reyes', 'Santa Cruz', 'Santa Cruz Island'],
    stats: { hp: 75, maxHp: 75, attack: 40, defense: 50, speed: 12 },
    isFantasy: false,
    sprite: '🦭',
    color: '#6b7280',
    activeTime: ['day', 'dawn'],
    moves: [
      { name: 'Trunk Blast', power: 35, type: 'special', description: 'Bellows with inflated nose' },
      { name: 'Body Slam', power: 40, type: 'attack', description: '5,000 lbs of impact' },
      { name: 'Blubber Shield', power: 0, type: 'defend', description: 'Thick blubber absorbs hits' },
    ],
  },
  {
    id: 'peregrine-falcon',
    name: 'Peregrine Falcon',
    scientificName: 'Falco peregrinus',
    description: 'The fastest animal on Earth, diving at over 240 mph to strike prey mid-flight.',
    lore: 'Nearly wiped out by DDT, peregrines have recovered spectacularly. They now nest on skyscrapers and bridges across California — the Bay Bridge, Transamerica Pyramid, and Salesforce Tower all host pairs. At 240+ mph, their stoops generate enough force to kill prey on impact.',
    type: 'bird',
    rarity: 'uncommon',
    biomes: ['urban', 'mountain', 'canyon'],
    subregions: ['San Francisco', 'Los Angeles', 'San Diego', 'Big Sur', 'Yosemite Valley'],
    stats: { hp: 30, maxHp: 30, attack: 52, defense: 18, speed: 60 },
    isFantasy: false,
    sprite: '🦅',
    color: '#374151',
    activeTime: ['day'],
    moves: [
      { name: 'Stoop', power: 50, type: 'attack', description: '240 mph death dive' },
      { name: 'Barrel Roll', power: 0, type: 'defend', description: 'Aerial evasion maneuver' },
      { name: 'Sonic Boom', power: 35, type: 'special', description: 'Shockwave from terminal velocity' },
    ],
  },
  {
    id: 'pacific-fisher',
    name: 'Pacific Fisher',
    scientificName: 'Pekania pennanti pacifica',
    description: 'An agile forest predator related to weasels, one of the few animals that hunts porcupines.',
    lore: 'Fishers are actually terrible at fishing — the name is a misnomer. The Southern Sierra population is critically endangered, threatened by rat poison from illegal marijuana grows on public lands. They are one of the few predators skilled enough to kill a porcupine, flipping it to attack the quill-free belly.',
    type: 'beast',
    rarity: 'rare',
    biomes: ['old_growth', 'forest'],
    subregions: ['Sequoia National Park', 'Yosemite Valley', 'Humboldt Redwoods', 'Prairie Creek Redwoods'],
    stats: { hp: 35, maxHp: 35, attack: 40, defense: 25, speed: 45 },
    isFantasy: false,
    sprite: '🦦',
    color: '#4a3728',
    activeTime: ['dawn', 'dusk', 'night'],
    moves: [
      { name: 'Porcupine Flip', power: 38, type: 'attack', description: 'Expert predatory technique' },
      { name: 'Tree Climb', power: 0, type: 'defend', description: 'Races up the nearest trunk' },
      { name: 'Musk Warning', power: 22, type: 'special', description: 'Mustelid defense spray' },
    ],
  },
  // === FANTASY CREATURES FOR NEW REGIONS ===
  {
    id: 'gold-rush-specter',
    name: 'Gold Rush Specter',
    scientificName: 'Spectrum aurum',
    description: 'The ghost of a Gold Rush miner, still panning for gold in the Sierra foothills streams.',
    lore: 'During the California Gold Rush, over 300,000 people flooded the Sierra foothills. Many never left. Rangers in the foothills report lantern lights moving along abandoned mine shafts at night, and the sound of pickaxes echoing from sealed tunnels. Some say they\'re still searching for the mother lode.',
    type: 'mystic',
    rarity: 'rare',
    biomes: ['canyon', 'mountain', 'forest'],
    subregions: ['Gold Country', 'Sacramento', 'Placerville'],
    stats: { hp: 40, maxHp: 40, attack: 35, defense: 30, speed: 38 },
    isFantasy: true,
    sprite: '⛏️',
    color: '#fbbf24',
    activeTime: ['night'],
    moves: [
      { name: 'Pickaxe Swing', power: 35, type: 'attack', description: 'Phantom mining tool strike' },
      { name: 'Tunnel Fade', power: 0, type: 'defend', description: 'Vanishes into mineshaft' },
      { name: 'Gold Dust', power: 30, type: 'special', description: 'Blinding swirl of gold flakes' },
    ],
  },
  {
    id: 'salton-djinn',
    name: 'Salton Djinn',
    scientificName: 'Daemon salinae',
    description: 'A shimmering entity rising from the toxic Salton Sea, smelling of sulfur and decay.',
    lore: 'The Salton Sea was created by accident in 1905 when an irrigation canal breached. Now shrinking and increasingly toxic, it spawns apocalyptic dust storms that blow across the Imperial Valley. Locals report a figure walking on the receding shoreline at sunset — part mirage, part something else.',
    type: 'mystic',
    rarity: 'legendary',
    biomes: ['desert', 'lakeshore'],
    subregions: ['Salton Sea', 'Anza-Borrego'],
    stats: { hp: 70, maxHp: 70, attack: 55, defense: 45, speed: 35 },
    isFantasy: true,
    sprite: '🌀',
    color: '#7c3aed',
    activeTime: ['dusk', 'night'],
    moves: [
      { name: 'Toxic Geyser', power: 50, type: 'attack', description: 'Eruption of poisonous brine' },
      { name: 'Dust Devil', power: 0, type: 'defend', description: 'Whirlwind of alkaline dust' },
      { name: 'Sulfur Curse', power: 45, type: 'special', description: 'Choking miasma of decay' },
    ],
  },
  {
    id: 'sequoia-titan',
    name: 'Sequoia Titan',
    scientificName: 'Colossus sequoiae',
    description: 'An ancient guardian spirit of the giant sequoia groves, as old as the trees themselves.',
    lore: 'Giant sequoias can live over 3,000 years. The General Sherman tree is the largest living organism on Earth by volume. Deep in the groves, where the trunks are so massive they seem to hold up the sky, rangers have documented movement that doesn\'t match any known animal. Something massive, and very old.',
    type: 'mystic',
    rarity: 'legendary',
    biomes: ['old_growth', 'forest'],
    subregions: ['Sequoia National Park', 'Kings Canyon'],
    stats: { hp: 90, maxHp: 90, attack: 45, defense: 70, speed: 10 },
    isFantasy: true,
    sprite: '🌲',
    color: '#854d0e',
    activeTime: ['dawn', 'dusk'],
    moves: [
      { name: 'Root Quake', power: 45, type: 'attack', description: 'Massive root system erupts' },
      { name: 'Bark Shield', power: 0, type: 'defend', description: '2-foot-thick bark deflects all' },
      { name: 'Ancient Growth', power: 50, type: 'special', description: '3,000 years of stored energy' },
    ],
  },
  {
    id: 'pacific-electric-ray',
    name: 'Pacific Electric Ray',
    scientificName: 'Tetronarce californica',
    description: 'A torpedo-shaped ray that generates electric shocks to stun prey in kelp forests.',
    lore: 'Pacific electric rays can generate up to 45 volts — enough to stun a diver who accidentally steps on one. They bury themselves in sand near kelp forests and ambush passing fish with an electric blast. They are one of the few animals on Earth that hunt with electricity.',
    type: 'marine',
    rarity: 'uncommon',
    biomes: ['water', 'kelp_forest', 'beach'],
    subregions: ['Monterey Bay', 'Santa Barbara', 'Santa Cruz Island', 'La Jolla'],
    stats: { hp: 40, maxHp: 40, attack: 42, defense: 30, speed: 25 },
    isFantasy: false,
    sprite: '🐟',
    color: '#374151',
    activeTime: ['day', 'night'],
    moves: [
      { name: 'Shock Pulse', power: 40, type: 'attack', description: '45-volt electrical discharge' },
      { name: 'Sand Bury', power: 0, type: 'defend', description: 'Vanishes under sand' },
      { name: 'Torpedo Rush', power: 30, type: 'special', description: 'Electric-charged charge' },
    ],
  },
  {
    id: 'tule-fog-wraith',
    name: 'Tule Fog Wraith',
    scientificName: 'Spectrum tularum',
    description: 'A ghostly presence that materializes in the thick tule fog of the Central Valley.',
    lore: 'Tule fog is California\'s deadliest weather — the thick ground radiation fog of the Central Valley causes deadly multi-car pileups every winter. Drivers on I-5 and Highway 99 report seeing figures in the fog that disappear when approached. The Valley has the highest fog-related fatality rate in the country.',
    type: 'mystic',
    rarity: 'rare',
    biomes: ['valley', 'marsh'],
    subregions: ['Bakersfield', 'Fresno', 'Stockton', 'Sacramento', 'Modesto'],
    stats: { hp: 45, maxHp: 45, attack: 38, defense: 35, speed: 42 },
    isFantasy: true,
    sprite: '🌫️',
    color: '#cbd5e1',
    activeTime: ['night', 'dawn'],
    moves: [
      { name: 'Fog Blind', power: 35, type: 'special', description: 'Impenetrable wall of fog' },
      { name: 'Ghost Touch', power: 30, type: 'attack', description: 'Chilling phantom grip' },
      { name: 'Mist Form', power: 0, type: 'defend', description: 'Becomes intangible fog' },
    ],
  },
]
