import type { Creature } from '@/types/game'

// ============================================================
// EXTENDED CREATURES — reptiles, plants, tidepool/chaparral/oak/
// kelp-forest species, and seasonal migrants. Added in a separate
// file to keep creatures.ts manageable. Conservation fields are
// embedded inline here; the map in creatures.ts does not touch them.
// ============================================================

export const EXTENDED_CREATURES: Creature[] = [
  // =========================
  // REPTILES
  // =========================
  {
    id: 'southern-alligator-lizard',
    name: 'Southern Alligator Lizard',
    scientificName: 'Elgaria multicarinata',
    description: 'A long-bodied lizard with a tail nearly twice its body length. Surprisingly aggressive when cornered.',
    lore: 'Southern alligator lizards are ubiquitous in Bay Area oak woodlands and chaparral, yet rarely seen because they spend much of their time under leaf litter. They will bite hard when handled and can shed their tail to escape predators — the detached tail keeps wriggling for up to a minute, distracting the attacker. They eat black widow spiders, making them valuable garden neighbors.',
    type: 'reptile',
    rarity: 'common',
    biomes: ['oak_woodland', 'chaparral', 'grassland'],
    subregions: ['Mt. Diablo', 'Rancho San Antonio', 'Sunol Regional Wilderness', 'Tilden Regional Park'],
    stats: { hp: 35, maxHp: 35, attack: 28, defense: 28, speed: 30 },
    isFantasy: false,
    sprite: '🦎',
    color: '#78350f',
    activeTime: ['dawn', 'day', 'dusk'],
    conservationStatus: 'LC',
    isNative: true,
    moves: [
      { name: 'Crushing Bite', power: 30, type: 'attack', description: 'A hard bite with powerful jaws' },
      { name: 'Tail Drop', power: 0, type: 'defend', description: 'Sheds tail as a distraction' },
      { name: 'Coil Strike', power: 28, type: 'special', description: 'Whips body in a coiled lash' },
    ],
  },
  {
    id: 'western-pond-turtle',
    name: 'Western Pond Turtle',
    scientificName: 'Actinemys marmorata',
    description: 'The only native freshwater turtle of California, basking on logs in quiet ponds and creeks.',
    lore: 'Western pond turtles once blanketed California waterways, but introduced bullfrogs, bass, and red-eared sliders have pushed them to near-threatened status. The Bay Area still holds small populations in quiet creeks and ponds — they bask on logs in the morning sun and plop into the water at the slightest disturbance. They can live over 50 years.',
    type: 'reptile',
    rarity: 'uncommon',
    biomes: ['marsh', 'water'],
    subregions: ['Don Edwards Wildlife Refuge', 'Baylands Nature Preserve', 'Tilden Regional Park'],
    stats: { hp: 50, maxHp: 50, attack: 20, defense: 55, speed: 12 },
    isFantasy: false,
    sprite: '🐢',
    color: '#365314',
    activeTime: ['dawn', 'day'],
    conservationStatus: 'VU',
    isNative: true,
    isEndemic: true,
    moves: [
      { name: 'Shell Slam', power: 28, type: 'attack', description: 'Charges with hardened shell' },
      { name: 'Withdraw', power: 0, type: 'defend', description: 'Retreats into impenetrable shell' },
      { name: 'Snapping Jaw', power: 32, type: 'special', description: 'A swift bite from a hidden head' },
    ],
  },
  {
    id: 'california-kingsnake',
    name: 'California Kingsnake',
    scientificName: 'Lampropeltis californiae',
    description: 'A bold black-and-white banded snake that preys on rattlesnakes. Immune to their venom.',
    lore: 'California kingsnakes are the Bay Area\'s most valuable reptile ally — they eat rattlesnakes, and their bodies have evolved immunity to pit viper venom. Their striking black-and-white banding warns predators away. They are gentle when handled and make their homes in brush piles and woodpiles throughout the chaparral and oak woodlands.',
    type: 'reptile',
    rarity: 'uncommon',
    biomes: ['chaparral', 'oak_woodland', 'grassland'],
    subregions: ['Mt. Diablo', 'Rancho San Antonio', 'Sunol Regional Wilderness'],
    stats: { hp: 40, maxHp: 40, attack: 38, defense: 28, speed: 30 },
    isFantasy: false,
    sprite: '🐍',
    color: '#171717',
    activeTime: ['dawn', 'day', 'dusk'],
    conservationStatus: 'LC',
    isNative: true,
    moves: [
      { name: 'King Bite', power: 36, type: 'attack', description: 'A venom-immune bite' },
      { name: 'Constrict', power: 30, type: 'attack', description: 'Squeezes the foe' },
      { name: 'Serpentine', power: 0, type: 'defend', description: 'Slithers nimbly aside' },
    ],
  },
  {
    id: 'ring-necked-snake',
    name: 'Ring-necked Snake',
    scientificName: 'Diadophis punctatus',
    description: 'A slender black snake with a yellow collar and fiery orange belly. Mildly venomous but harmless to humans.',
    lore: 'When threatened, ring-necked snakes curl their tails to display the vivid orange underside — a warning to predators. They are nocturnal hunters of salamanders and slugs in the damp leaf litter of redwood and oak forests. Despite being mildly venomous (to their small prey), they are utterly harmless to humans.',
    type: 'reptile',
    rarity: 'common',
    biomes: ['forest', 'redwood', 'oak_woodland'],
    subregions: ['Muir Woods', 'Redwood Regional Park', 'Tilden Regional Park'],
    stats: { hp: 25, maxHp: 25, attack: 22, defense: 18, speed: 32 },
    isFantasy: false,
    sprite: '🐍',
    color: '#f97316',
    activeTime: ['dusk', 'night'],
    conservationStatus: 'LC',
    isNative: true,
    moves: [
      { name: 'Warning Curl', power: 0, type: 'defend', description: 'Coils to flash orange belly' },
      { name: 'Quick Strike', power: 22, type: 'attack', description: 'Lightning-fast snap' },
      { name: 'Mild Venom', power: 20, type: 'special', description: 'A slow-acting toxic bite' },
    ],
  },

  // =========================
  // PLANTS
  // =========================
  {
    id: 'california-poppy',
    name: 'California Poppy',
    scientificName: 'Eschscholzia californica',
    description: 'The state flower of California, blanketing hillsides in fiery orange during spring.',
    lore: 'The California poppy is the official state flower, and every spring its blaze of orange transforms the grasslands of Mt. Diablo, the Carrizo Plain, and the East Bay hills. The flower closes each evening and on cloudy days, protecting its pollen. Native people used it as a mild sedative, and it is entirely endemic to California and Baja.',
    type: 'plant',
    rarity: 'common',
    biomes: ['grassland', 'chaparral', 'oak_woodland'],
    subregions: ['Mt. Diablo', 'Rancho San Antonio', 'Sunol Regional Wilderness', 'Tilden Regional Park'],
    stats: { hp: 20, maxHp: 20, attack: 15, defense: 20, speed: 10 },
    isFantasy: false,
    sprite: '🌼',
    color: '#f97316',
    activeTime: ['dawn', 'day'],
    conservationStatus: 'LC',
    isNative: true,
    isEndemic: true,
    moves: [
      { name: 'Pollen Puff', power: 18, type: 'special', description: 'A sedating cloud of orange pollen' },
      { name: 'Close Petals', power: 0, type: 'defend', description: 'Wraps tight at dusk' },
      { name: 'Sunburst', power: 22, type: 'attack', description: 'Unfurls at dawn in a blaze of color' },
    ],
  },
  {
    id: 'coast-live-oak',
    name: 'Coast Live Oak',
    scientificName: 'Quercus agrifolia',
    description: 'A gnarled, evergreen oak that anchors the Bay Area savannas. Its acorns feed a whole ecosystem.',
    lore: 'Coast live oaks are the keystone species of California oak woodlands. A single mature tree can produce 2,000 pounds of acorns a year, feeding deer, squirrels, acorn woodpeckers, and once, the Ohlone people, who cultivated and tended the oak woodlands for millennia. They can live 250 years and host more biodiversity than any other Bay Area tree.',
    type: 'plant',
    rarity: 'common',
    biomes: ['oak_woodland', 'grassland', 'forest'],
    subregions: ['Mt. Diablo', 'Rancho San Antonio', 'Sunol Regional Wilderness', 'Tilden Regional Park', 'Briones Regional Park'],
    stats: { hp: 80, maxHp: 80, attack: 25, defense: 60, speed: 5 },
    isFantasy: false,
    sprite: '🌳',
    color: '#365314',
    activeTime: ['dawn', 'day', 'dusk', 'night'],
    conservationStatus: 'LC',
    isNative: true,
    moves: [
      { name: 'Acorn Barrage', power: 30, type: 'attack', description: 'Rains hard acorns down' },
      { name: 'Bark Guard', power: 0, type: 'defend', description: 'Thickens corky bark' },
      { name: 'Root Grasp', power: 28, type: 'special', description: 'Ancient roots entangle the foe' },
    ],
  },
  {
    id: 'coast-redwood-sapling',
    name: 'Coast Redwood Sapling',
    scientificName: 'Sequoia sempervirens',
    description: 'A young giant — even small, it grows a foot each year on its way to becoming the tallest tree on Earth.',
    lore: 'Coast redwoods are the tallest trees on Earth, reaching over 380 feet. They are endemic to the fog belt of the California coast and depend on summer fog drip for water. Old-growth redwoods can live over 2,000 years, and even a sapling carries the genetic memory of ancestors that predate the Roman Empire. They survive by clonal sprouting when their parents fell.',
    type: 'plant',
    rarity: 'uncommon',
    biomes: ['redwood', 'forest'],
    subregions: ['Muir Woods', 'Purisima Creek Redwoods', 'Redwood Regional Park'],
    stats: { hp: 60, maxHp: 60, attack: 22, defense: 55, speed: 8 },
    isFantasy: false,
    sprite: '🌲',
    color: '#7c2d12',
    activeTime: ['dawn', 'day', 'dusk', 'night'],
    conservationStatus: 'NT',
    isNative: true,
    isEndemic: true,
    moves: [
      { name: 'Fog Drip', power: 25, type: 'special', description: 'Calls moisture from the marine layer' },
      { name: 'Tannin Shield', power: 0, type: 'defend', description: 'Releases bitter tannins' },
      { name: 'Branch Sweep', power: 28, type: 'attack', description: 'A sweeping evergreen bough' },
    ],
  },
  {
    id: 'toyon',
    name: 'Toyon',
    scientificName: 'Heteromeles arbutifolia',
    description: 'The "Christmas berry" shrub of California chaparral, its bright red berries feeding wintering birds.',
    lore: 'Toyon is so iconic that it inspired the name "Hollywood" — early settlers mistook its bright red winter berries for holly. It is the last surviving member of its genus and is entirely endemic to California. Its berries feed cedar waxwings and robins through the dry winter, and its dense evergreen foliage provides crucial cover in the chaparral.',
    type: 'plant',
    rarity: 'common',
    biomes: ['chaparral', 'oak_woodland'],
    subregions: ['Mt. Diablo', 'Mt. Tamalpais', 'Oakland Hills', 'Sunol Regional Wilderness'],
    stats: { hp: 40, maxHp: 40, attack: 20, defense: 35, speed: 10 },
    isFantasy: false,
    sprite: '🌿',
    color: '#dc2626',
    activeTime: ['dawn', 'day', 'dusk'],
    conservationStatus: 'LC',
    isNative: true,
    isEndemic: true,
    moves: [
      { name: 'Berry Burst', power: 25, type: 'attack', description: 'Pelts the foe with ripe red berries' },
      { name: 'Thornwall', power: 0, type: 'defend', description: 'Raises a dense evergreen hedge' },
      { name: 'Cyanide Leaf', power: 22, type: 'special', description: 'Releases bitter hydrocyanic compounds' },
    ],
  },
  {
    id: 'giant-kelp',
    name: 'Giant Kelp',
    scientificName: 'Macrocystis pyrifera',
    description: 'Towering underwater forests off the Pacific coast, swaying up to 150 feet from holdfast to canopy.',
    lore: 'Giant kelp is the fastest-growing organism on Earth, extending up to two feet per day. Off the California coast, kelp forests rival redwoods in their ecological complexity, sheltering sea otters, garibaldi, and countless invertebrates. Climate-driven marine heatwaves and exploding urchin populations have devastated many forests, making each surviving stand a vital refuge.',
    type: 'plant',
    rarity: 'uncommon',
    biomes: ['kelp_forest', 'water'],
    subregions: ['Point Reyes', 'Half Moon Bay', 'Pacifica', 'Santa Cruz Coast'],
    stats: { hp: 50, maxHp: 50, attack: 18, defense: 42, speed: 18 },
    isFantasy: false,
    sprite: '🌿',
    color: '#166534',
    activeTime: ['dawn', 'day', 'dusk'],
    conservationStatus: 'LC',
    isNative: true,
    moves: [
      { name: 'Kelp Lash', power: 25, type: 'attack', description: 'Whips with a long frond' },
      { name: 'Canopy Sway', power: 0, type: 'defend', description: 'Flows with the current to deflect blows' },
      { name: 'Tangle Net', power: 22, type: 'special', description: 'Wraps the foe in stipe and blade' },
    ],
  },

  // =========================
  // TIDEPOOL
  // =========================
  {
    id: 'ochre-sea-star',
    name: 'Ochre Sea Star',
    scientificName: 'Pisaster ochraceus',
    description: 'A purple or orange five-armed sea star clinging to tidepool rocks. A keystone predator.',
    lore: 'The ochre sea star is the original "keystone species" — the ecologist Robert Paine coined the term in 1969 after studying how its removal collapsed entire tidepool ecosystems. Since 2013, a mysterious wasting disease has killed millions of ochre stars along the Pacific coast. Bay Area tidepools at Fitzgerald Marine Reserve and Pillar Point still hold small populations — every sighting is precious.',
    type: 'marine',
    rarity: 'uncommon',
    biomes: ['tidepool', 'beach'],
    subregions: ['Pacifica', 'Half Moon Bay'],
    stats: { hp: 45, maxHp: 45, attack: 25, defense: 45, speed: 5 },
    isFantasy: false,
    sprite: '⭐',
    color: '#7c3aed',
    activeTime: ['dawn', 'day', 'dusk', 'night'],
    conservationStatus: 'VU',
    isNative: true,
    moves: [
      { name: 'Arm Grip', power: 28, type: 'attack', description: 'Tube feet grip and pull' },
      { name: 'Stomach Evert', power: 30, type: 'special', description: 'Digests prey outside its body' },
      { name: 'Cling', power: 0, type: 'defend', description: 'Anchors immovably to stone' },
    ],
  },
  {
    id: 'hermit-crab',
    name: 'Pacific Hermit Crab',
    scientificName: 'Pagurus samuelis',
    description: 'A tiny crab living inside a borrowed snail shell, scuttling through tidepools.',
    lore: 'Pacific hermit crabs are tidepool fixtures, constantly trading up shells as they grow. At low tide, a line of them may form near a newly-vacated shell, each taking the next-largest home in a perfectly ordered exchange. They scavenge everything from algae to dead fish, keeping the tidepools clean.',
    type: 'marine',
    rarity: 'common',
    biomes: ['tidepool', 'beach'],
    subregions: ['Pacifica', 'Half Moon Bay', 'North Beach / Fishermans Wharf'],
    stats: { hp: 22, maxHp: 22, attack: 18, defense: 40, speed: 18 },
    isFantasy: false,
    sprite: '🦀',
    color: '#c2410c',
    activeTime: ['dawn', 'day', 'dusk', 'night'],
    conservationStatus: 'LC',
    isNative: true,
    moves: [
      { name: 'Claw Pinch', power: 20, type: 'attack', description: 'A surprisingly strong pinch' },
      { name: 'Shell Swap', power: 0, type: 'defend', description: 'Ducks into its borrowed shell' },
      { name: 'Scuttle', power: 15, type: 'special', description: 'Darts under a rock' },
    ],
  },
  {
    id: 'tidepool-sculpin',
    name: 'Tidepool Sculpin',
    scientificName: 'Oligocottus maculosus',
    description: 'A tiny mottled fish that changes color to match its pool, remembering home from hundreds of feet away.',
    lore: 'Tidepool sculpins have an uncanny homing instinct — experiments show they can find their home pool even after being moved over 300 feet. They change color over minutes to match the algae around them, becoming nearly invisible. At low tide, they huddle under rocks, breathing through damp gills until the ocean returns.',
    type: 'marine',
    rarity: 'common',
    biomes: ['tidepool'],
    subregions: ['Pacifica', 'Half Moon Bay'],
    stats: { hp: 25, maxHp: 25, attack: 22, defense: 20, speed: 32 },
    isFantasy: false,
    sprite: '🐟',
    color: '#44403c',
    activeTime: ['dawn', 'day', 'dusk'],
    conservationStatus: 'LC',
    isNative: true,
    moves: [
      { name: 'Tidepool Dart', power: 25, type: 'attack', description: 'Zips through the water' },
      { name: 'Color Shift', power: 0, type: 'defend', description: 'Blends perfectly with surroundings' },
      { name: 'Home Pool', power: 18, type: 'special', description: 'Calls on the memory of home' },
    ],
  },

  // =========================
  // CHAPARRAL
  // =========================
  {
    id: 'california-thrasher',
    name: 'California Thrasher',
    scientificName: 'Toxostoma redivivum',
    description: 'A long-tailed, curve-billed songbird that sings elaborate mimic songs from the chaparral tops.',
    lore: 'The California thrasher is one of only a few birds truly endemic to the California floristic province. It mimics the songs of dozens of other birds, stringing them into rambling concerts from atop a chamise bush. Its long curved bill is perfect for raking through leaf litter under manzanita. Bay Area populations persist on Mt. Diablo and in the East Bay chaparral.',
    type: 'bird',
    rarity: 'uncommon',
    biomes: ['chaparral', 'oak_woodland'],
    subregions: ['Mt. Diablo', 'Sunol Regional Wilderness', 'Oakland Hills'],
    stats: { hp: 32, maxHp: 32, attack: 30, defense: 20, speed: 38 },
    isFantasy: false,
    sprite: '🐦',
    color: '#78350f',
    activeTime: ['dawn', 'day', 'dusk'],
    conservationStatus: 'LC',
    isNative: true,
    isEndemic: true,
    moves: [
      { name: 'Curved Bill', power: 28, type: 'attack', description: 'Rakes with a curved bill' },
      { name: 'Mimic Chorus', power: 25, type: 'special', description: 'Mimics a dozen bird calls' },
      { name: 'Brush Dash', power: 0, type: 'defend', description: 'Vanishes into dense brush' },
    ],
  },
  {
    id: 'wrentit',
    name: 'Wrentit',
    scientificName: 'Chamaea fasciata',
    description: 'A tiny brown bird whose bouncing-ball song is the voice of California chaparral.',
    lore: 'The wrentit is unique — the only American member of its family — and is considered the quintessential chaparral bird. Its accelerating "bouncing ball" song is the sound of dawn in every Bay Area scrub habitat. Wrentits mate for life and rarely venture more than a few hundred feet from where they hatched.',
    type: 'bird',
    rarity: 'common',
    biomes: ['chaparral', 'oak_woodland'],
    subregions: ['Mt. Diablo', 'Marin Headlands', 'Oakland Hills', 'Sunol Regional Wilderness'],
    stats: { hp: 22, maxHp: 22, attack: 20, defense: 15, speed: 35 },
    isFantasy: false,
    sprite: '🐦',
    color: '#92400e',
    activeTime: ['dawn', 'day', 'dusk'],
    conservationStatus: 'LC',
    isNative: true,
    moves: [
      { name: 'Bouncing Song', power: 22, type: 'special', description: 'An accelerating hypnotic tune' },
      { name: 'Brush Dart', power: 18, type: 'attack', description: 'A quick strike from hiding' },
      { name: 'Thicket Hide', power: 0, type: 'defend', description: 'Disappears into the scrub' },
    ],
  },
  {
    id: 'annas-hummingbird',
    name: 'Anna\'s Hummingbird',
    scientificName: 'Calypte anna',
    description: 'An iridescent hummingbird that dive-bombs at 60 mph, its throat flashing magenta in the sun.',
    lore: 'Anna\'s hummingbirds are the only hummingbird that stays in the Bay Area year-round. Males perform courtship dives from 130 feet, producing a sharp "chirp" with their tail feathers at the bottom. Their iridescent magenta throats look dull gray from most angles but explode with color when sunlight hits them just right.',
    type: 'bird',
    rarity: 'common',
    biomes: ['chaparral', 'urban', 'oak_woodland', 'forest'],
    subregions: ['Golden Gate Park', 'The Presidio', 'Berkeley', 'Mt. Diablo', 'Tilden Regional Park'],
    stats: { hp: 18, maxHp: 18, attack: 25, defense: 12, speed: 60 },
    isFantasy: false,
    sprite: '🐦',
    color: '#ec4899',
    activeTime: ['dawn', 'day', 'dusk'],
    conservationStatus: 'LC',
    isNative: true,
    moves: [
      { name: 'Dive Bomb', power: 30, type: 'attack', description: 'A 60 mph courtship dive' },
      { name: 'Hover Strike', power: 22, type: 'attack', description: 'Hovers and darts in' },
      { name: 'Gorget Flash', power: 0, type: 'defend', description: 'Blinding iridescent throat' },
    ],
  },

  // === OAK WOODLAND ===
  {
    id: 'acorn-woodpecker',
    name: 'Acorn Woodpecker',
    scientificName: 'Melanerpes formicivorus',
    description: 'A clownish black-and-white woodpecker with a red crown that stores thousands of acorns in tree "granaries".',
    lore: 'Acorn woodpeckers live in cooperative family groups and drill thousands of holes into dead trees, each one holding a single acorn. A single granary tree can store 50,000 acorns. They defend their stash fiercely and call constantly — a loud "waka-waka-waka" that echoes through oak woodlands.',
    type: 'bird',
    rarity: 'common',
    biomes: ['oak_woodland', 'forest'],
    subregions: ['Mt. Diablo', 'Sunol Regional Wilderness', 'Henry W. Coe State Park'],
    stats: { hp: 55, maxHp: 55, attack: 22, defense: 16, speed: 26 },
    isFantasy: false,
    sprite: '🪶',
    color: '#dc2626',
    activeTime: ['dawn', 'day'],
    conservationStatus: 'LC',
    isNative: true,
    moves: [
      { name: 'Granary Peck', power: 24, type: 'attack', description: 'Stores acorns in tree holes' },
      { name: 'Communal Call', power: 0, type: 'defend', description: 'Rallies the flock' },
      { name: 'Drill Strike', power: 28, type: 'attack', description: 'Hammers at high speed' },
    ],
  },
  {
    id: 'western-bluebird',
    name: 'Western Bluebird',
    scientificName: 'Sialia mexicana',
    description: 'A small thrush with dazzling cobalt-blue plumage and a rust-orange breast, fond of oak savannas.',
    lore: 'Western bluebirds nest in old woodpecker holes in oak trees — the acorn woodpeckers unwittingly build their homes. They perch on low branches and drop to the ground to snatch insects. Conservation nest-box programs have helped rebuild their Bay Area populations after decades of decline.',
    type: 'bird',
    rarity: 'common',
    biomes: ['oak_woodland', 'grassland'],
    subregions: ['Mt. Diablo', 'Briones Regional Park', 'Sunol Regional Wilderness'],
    stats: { hp: 48, maxHp: 48, attack: 20, defense: 14, speed: 28 },
    isFantasy: false,
    sprite: '🐦',
    color: '#3b82f6',
    activeTime: ['dawn', 'day', 'dusk'],
    conservationStatus: 'LC',
    isNative: true,
    moves: [
      { name: 'Swoop', power: 22, type: 'attack', description: 'Glides down on prey' },
      { name: 'Insect Snatch', power: 18, type: 'attack', description: 'Plucks bugs midair' },
      { name: 'Azure Flash', power: 0, type: 'defend', description: 'Startling wing display' },
    ],
  },
  {
    id: 'oak-titmouse',
    name: 'Oak Titmouse',
    scientificName: 'Baeolophus inornatus',
    description: 'A small crested gray songbird utterly tied to California oak woodlands — its entire range is the oak belt.',
    lore: 'The oak titmouse is the "voice of the oaks" in California. It rarely leaves oak woodland and its range maps perfectly onto oak distribution. When oaks die from sudden oak death or development, titmice vanish with them. They mate for life and defend year-round territories.',
    type: 'bird',
    rarity: 'uncommon',
    biomes: ['oak_woodland'],
    subregions: ['Mt. Diablo', 'Briones Regional Park', 'Sunol Regional Wilderness', 'Henry W. Coe State Park'],
    stats: { hp: 42, maxHp: 42, attack: 18, defense: 14, speed: 30 },
    isFantasy: false,
    sprite: '🐤',
    color: '#a16207',
    activeTime: ['dawn', 'day'],
    conservationStatus: 'LC',
    isNative: true,
    isEndemic: true,
    moves: [
      { name: 'Seed Crack', power: 20, type: 'attack', description: 'Hammers open acorns' },
      { name: 'Crested Alarm', power: 0, type: 'defend', description: 'Raises crest to warn' },
      { name: 'Canopy Dart', power: 22, type: 'attack', description: 'Weaves through oak branches' },
    ],
  },

  // === KELP FOREST ===
  {
    id: 'leopard-shark',
    name: 'Leopard Shark',
    scientificName: 'Triakis semifasciata',
    description: 'A slender, patterned shark cruising bay shallows and kelp beds — harmless to humans.',
    lore: 'Leopard sharks gather in big schools inside San Francisco Bay every summer, sometimes hundreds swimming right off the beach. They are so docile you can wade among them. They feed on crabs, clams, and small fish, and live over 30 years.',
    type: 'marine',
    rarity: 'uncommon',
    biomes: ['kelp_forest', 'water', 'beach'],
    subregions: ['The Presidio', 'Elkhorn Slough', 'Half Moon Bay'],
    stats: { hp: 75, maxHp: 75, attack: 26, defense: 20, speed: 22 },
    isFantasy: false,
    sprite: '🦈',
    color: '#6b7280',
    conservationStatus: 'LC',
    isNative: true,
    moves: [
      { name: 'Sand Glide', power: 24, type: 'attack', description: 'Cruises the shallows' },
      { name: 'Suction Gulp', power: 28, type: 'attack', description: 'Vacuums up crabs and fish' },
      { name: 'Spotted Camouflage', power: 0, type: 'defend', description: 'Blends with dappled sand' },
    ],
  },
  {
    id: 'california-sea-hare',
    name: 'California Sea Hare',
    scientificName: 'Aplysia californica',
    description: 'A massive sea slug the size of a football, ballooning purple-brown through kelp and tidepools.',
    lore: 'California sea hares can grow over two feet long and weigh 15 pounds. When threatened they release a thick cloud of purple ink that confuses predators. Their simple nervous system — huge, easily-studied neurons — made them a cornerstone of neuroscience research. They are hermaphrodites and can chain-mate in long conga lines of five or more.',
    type: 'marine',
    rarity: 'uncommon',
    biomes: ['kelp_forest', 'tidepool'],
    subregions: ['Half Moon Bay', 'Fitzgerald Marine Reserve', 'Pacifica'],
    stats: { hp: 60, maxHp: 60, attack: 14, defense: 26, speed: 10 },
    isFantasy: false,
    sprite: '🐌',
    color: '#7c3aed',
    conservationStatus: 'LC',
    isNative: true,
    moves: [
      { name: 'Ink Cloud', power: 0, type: 'defend', description: 'Releases purple ink to escape' },
      { name: 'Graze', power: 16, type: 'attack', description: 'Chews on red algae' },
      { name: 'Toxic Slime', power: 22, type: 'attack', description: 'Secretes noxious chemicals' },
    ],
  },

  // =========================
  // SEASONAL MIGRANTS
  // =========================
  {
    id: 'chinook-salmon',
    name: 'Chinook Salmon',
    scientificName: 'Oncorhynchus tshawytscha',
    description: 'The king of Pacific salmon, returning up rivers each fall to spawn where it was born.',
    lore: 'Chinook salmon hatch in Bay Area rivers, migrate to the open Pacific for years, then return to the exact stream of their birth to spawn and die. Their fall run up the Sacramento and American rivers was once so thick you could cross the river on their backs. Dams and diversions have pushed the spring run to endangered status; the fall run hangs on as a fragile miracle of navigation.',
    type: 'marine',
    rarity: 'rare',
    biomes: ['water', 'marsh'],
    subregions: ['Sacramento River', 'American River', 'Mokelumne River'],
    stats: { hp: 75, maxHp: 75, attack: 32, defense: 22, speed: 30 },
    isFantasy: false,
    sprite: '🐟',
    color: '#b91c1c',
    conservationStatus: 'VU',
    isNative: true,
    migrationWindow: { startMonth: 8, endMonth: 10 },
    moves: [
      { name: 'Upstream Surge', power: 32, type: 'attack', description: 'Leaps a waterfall with raw power' },
      { name: 'Spawning Thrash', power: 28, type: 'attack', description: 'Defends a redd with violent turns' },
      { name: 'Homing Instinct', power: 0, type: 'defend', description: 'Navigates by scent and stars' },
    ],
  },
  {
    id: 'gray-whale',
    name: 'Gray Whale',
    scientificName: 'Eschrichtius robustus',
    description: 'A barnacle-encrusted giant passing the California coast on the longest mammal migration on Earth.',
    lore: 'Gray whales swim 12,000 miles round-trip each year between Arctic feeding grounds and Baja breeding lagoons. Every winter and spring they parade past the Bay Area coast, visible from Point Reyes, Pigeon Point, and the Marin Headlands. Nearly wiped out by whaling twice, they have recovered remarkably. Mothers and calves hug the coast in spring to avoid orcas.',
    type: 'marine',
    rarity: 'legendary',
    biomes: ['water', 'beach'],
    subregions: ['Point Reyes', 'Half Moon Bay', 'Marin Headlands', 'Montara'],
    stats: { hp: 120, maxHp: 120, attack: 30, defense: 45, speed: 18 },
    isFantasy: false,
    sprite: '🐋',
    color: '#475569',
    conservationStatus: 'LC',
    isNative: true,
    migrationWindow: { startMonth: 11, endMonth: 4 },
    moves: [
      { name: 'Fluke Slam', power: 38, type: 'attack', description: 'Massive tail strike' },
      { name: 'Spyhop', power: 0, type: 'defend', description: 'Rises to scan for danger' },
      { name: 'Deep Dive', power: 30, type: 'special', description: 'Disappears into open water' },
    ],
  },
  {
    id: 'vauxs-swift',
    name: "Vaux's Swift",
    scientificName: 'Chaetura vauxi',
    description: 'A tiny cigar-shaped bird that pours by the thousands into chimneys during spring migration.',
    lore: 'Every spring, Vaux\'s swifts migrate north through the Bay Area on their way from Central America to Pacific Northwest forests. They roost communally in old brick chimneys, sometimes 10,000 at a time, funneling down at dusk in a breathtaking black tornado. The Chapman Elementary roost in Portland is famous, but Bay Area chimneys host their own smaller wonders.',
    type: 'bird',
    rarity: 'rare',
    biomes: ['urban', 'forest', 'redwood'],
    subregions: ['McNears Brickyard', 'San Rafael', 'Downtown Oakland'],
    stats: { hp: 38, maxHp: 38, attack: 18, defense: 12, speed: 55 },
    isFantasy: false,
    sprite: '🐦',
    color: '#44403c',
    activeTime: ['dawn', 'day', 'dusk'],
    conservationStatus: 'LC',
    isNative: true,
    migrationWindow: { startMonth: 2, endMonth: 4 },
    moves: [
      { name: 'Aerial Snap', power: 22, type: 'attack', description: 'Snatches insects in flight' },
      { name: 'Chimney Swirl', power: 0, type: 'defend', description: 'Spirals into a safe roost' },
      { name: 'Continental Dash', power: 28, type: 'special', description: 'Migrates thousands of miles' },
    ],
  },

  // =========================
  // INVASIVE SPECIES
  // =========================
  {
    id: 'american-bullfrog',
    name: 'American Bullfrog',
    scientificName: 'Lithobates catesbeianus',
    description: 'A massive green frog introduced from the east that eats anything smaller than itself — including native frogs.',
    lore: 'American bullfrogs were brought to California in the 1800s as a food source and now dominate ponds and creeks statewide. They eat native red-legged frogs, Western pond turtle hatchlings, dragonflies, mice, and even small birds. A single bullfrog can lay 20,000 eggs. They are a leading cause of native amphibian decline.',
    type: 'amphibian',
    rarity: 'common',
    biomes: ['marsh', 'water'],
    subregions: ['Don Edwards Wildlife Refuge', 'Baylands Nature Preserve', 'Lake Merced'],
    stats: { hp: 70, maxHp: 70, attack: 30, defense: 22, speed: 14 },
    isFantasy: false,
    sprite: '🐸',
    color: '#166534',
    activeTime: ['dusk', 'night'],
    conservationStatus: 'INV',
    isNative: false,
    moves: [
      { name: 'Gulping Bite', power: 32, type: 'attack', description: 'Swallows prey whole' },
      { name: 'Territorial Bellow', power: 0, type: 'defend', description: 'A deep "jug-o-rum" call' },
      { name: 'Tongue Snap', power: 24, type: 'attack', description: 'Lightning-fast tongue strike' },
    ],
  },
  {
    id: 'european-starling',
    name: 'European Starling',
    scientificName: 'Sturnus vulgaris',
    description: 'A glossy black bird introduced from Europe, flocking in the millions and displacing native cavity nesters.',
    lore: 'Every European starling in North America descends from 100 birds released in New York\'s Central Park in 1890 by a Shakespeare enthusiast who wanted all the birds mentioned in the plays. They now number 200 million and aggressively evict bluebirds, woodpeckers, and owls from nest cavities. Their oil-slick plumage looks beautiful but signals an ecological disaster.',
    type: 'bird',
    rarity: 'common',
    biomes: ['urban', 'grassland', 'oak_woodland'],
    subregions: ['Financial District', 'Downtown Oakland', 'San Rafael'],
    stats: { hp: 40, maxHp: 40, attack: 22, defense: 14, speed: 32 },
    isFantasy: false,
    sprite: '🐦',
    color: '#0f172a',
    activeTime: ['dawn', 'day', 'dusk'],
    conservationStatus: 'INV',
    isNative: false,
    moves: [
      { name: 'Nest Raid', power: 26, type: 'attack', description: 'Evicts native cavity nesters' },
      { name: 'Murmuration', power: 0, type: 'defend', description: 'Joins a swirling flock' },
      { name: 'Mimic Song', power: 20, type: 'special', description: 'Imitates other birds to confuse' },
    ],
  },
  {
    id: 'red-eared-slider',
    name: 'Red-Eared Slider',
    scientificName: 'Trachemys scripta elegans',
    description: 'A pet-trade turtle released into ponds, outcompeting native Western Pond Turtles for basking spots and food.',
    lore: 'Red-eared sliders are sold by the millions in pet stores, then released when they grow too big or live too long. In California ponds they crowd out native Western pond turtles, hog basking logs, and carry diseases. They are one of the 100 worst invasive species in the world according to the IUCN.',
    type: 'reptile',
    rarity: 'common',
    biomes: ['marsh', 'water', 'urban'],
    subregions: ['Stow Lake', 'Lake Merritt', 'Lake Merced'],
    stats: { hp: 55, maxHp: 55, attack: 20, defense: 48, speed: 10 },
    isFantasy: false,
    sprite: '🐢',
    color: '#059669',
    activeTime: ['day'],
    conservationStatus: 'INV',
    isNative: false,
    moves: [
      { name: 'Shell Slam', power: 24, type: 'attack', description: 'Rams with a hard carapace' },
      { name: 'Basking Hog', power: 0, type: 'defend', description: 'Claims the best basking log' },
      { name: 'Snap Bite', power: 22, type: 'attack', description: 'Quick underwater bite' },
    ],
  },
]
