import type { Creature } from '@/types/game'

export const NEW_SPECIES: Creature[] = [
  {
    id: 'joshua-tree-lizard',
    name: 'Joshua Tree Lizard',
    scientificName: 'Sceloporus magister',
    description: 'A heat-loving lizard that basks on sun-baked rocks among the Joshua trees.',
    type: 'reptile',
    rarity: 'common',
    biomes: ['desert', 'scrubland'],
    subregions: ['Joshua Tree', 'Mojave Desert'],
    stats: { hp: 28, maxHp: 28, attack: 22, defense: 18, speed: 35 },
    isFantasy: false,
    sprite: '🦎',
    color: '#a16207',
    activeTime: ['day'],
    conservationStatus: 'LC',
    isNative: true,
    moves: [
      { name: 'Sand Dash', power: 18, type: 'attack', description: 'Quick strike from the sand' },
      { name: 'Heat Bask', power: 0, type: 'defend', description: 'Absorbs heat to boost speed' },
    ],
  },
  {
    id: 'mountain-yellow-legged-frog',
    name: 'Mountain Yellow-legged Frog',
    scientificName: 'Rana muscosa',
    description: 'A critically endangered frog found only in high Sierra lakes.',
    type: 'amphibian',
    rarity: 'rare',
    biomes: ['alpine', 'water'],
    subregions: ['Yosemite', 'Sequoia', 'Kings Canyon'],
    stats: { hp: 35, maxHp: 35, attack: 22, defense: 25, speed: 30 },
    isFantasy: false,
    sprite: '🐸',
    color: '#a3e635',
    activeTime: ['day', 'dusk'],
    conservationStatus: 'CR',
    isNative: true,
    isEndemic: true,
    moves: [
      { name: 'Toxic Skin', power: 20, type: 'special', description: 'Exudes defensive toxins' },
      { name: 'Alpine Splash', power: 22, type: 'attack', description: 'Leaps from glacial water' },
      { name: 'Survival Croak', power: 0, type: 'defend', description: 'Resilience from near-extinction' },
    ],
  },
  {
    id: 'channel-island-fox',
    name: 'Channel Island Fox',
    scientificName: 'Urocyon littoralis',
    description: 'A tiny fox found nowhere else on Earth, each island has its own subspecies.',
    type: 'beast',
    rarity: 'rare',
    biomes: ['chaparral', 'grassland'],
    subregions: ['Santa Cruz Island', 'Santa Catalina Island'],
    stats: { hp: 38, maxHp: 38, attack: 28, defense: 22, speed: 38 },
    isFantasy: false,
    sprite: '🦊',
    color: '#9a3412',
    activeTime: ['dusk', 'night'],
    conservationStatus: 'NT',
    isNative: true,
    isEndemic: true,
    moves: [
      { name: 'Island Pounce', power: 25, type: 'attack', description: 'Quick predatory leap' },
      { name: 'Foraging Bite', power: 20, type: 'attack', description: 'Opportunistic snap' },
    ],
  },
  {
    id: 'rough-skinned-newt',
    name: 'Rough-skinned Newt',
    scientificName: 'Taricha granulosa',
    description: 'Produces enough tetrodotoxin to kill an adult human — do not touch.',
    type: 'amphibian',
    rarity: 'uncommon',
    biomes: ['forest', 'redwood', 'marsh'],
    subregions: ['Tilden Regional Park', 'Muir Woods', 'Big Basin', 'Henry Cowell'],
    stats: { hp: 32, maxHp: 32, attack: 18, defense: 35, speed: 15 },
    isFantasy: false,
    sprite: '🦎',
    color: '#ea580c',
    activeTime: ['dawn', 'dusk', 'night'],
    activeWeather: ['rain', 'fog'],
    conservationStatus: 'LC',
    isNative: true,
    moves: [
      { name: 'Toxic Warning', power: 20, type: 'special', description: 'Flashes bright orange belly' },
      { name: 'Poison Skin', power: 0, type: 'defend', description: 'Lethal toxin deters attackers' },
    ],
  },
  {
    id: 'giant-kangaroo-rat',
    name: 'Giant Kangaroo Rat',
    scientificName: 'Dipodomys ingens',
    description: 'An endangered nocturnal rodent that drums its feet to communicate.',
    type: 'beast',
    rarity: 'rare',
    biomes: ['grassland', 'scrubland', 'valley'],
    subregions: ['Bakersfield', 'San Luis Obispo'],
    stats: { hp: 22, maxHp: 22, attack: 18, defense: 15, speed: 45 },
    isFantasy: false,
    sprite: '🐀',
    color: '#d4a574',
    activeTime: ['night'],
    conservationStatus: 'EN',
    isNative: true,
    isEndemic: true,
    moves: [
      { name: 'Foot Drum', power: 18, type: 'special', description: 'Rapid drumming stuns foe' },
      { name: 'Leap Dodge', power: 0, type: 'defend', description: 'Incredible vertical leap' },
      { name: 'Seed Fling', power: 15, type: 'attack', description: 'Hurls cached seeds' },
    ],
  },
  {
    id: 'garibaldi-fish',
    name: 'Garibaldi',
    scientificName: 'Hypsypops rubicundus',
    description: 'California\'s state marine fish — a brilliant orange damselfish fiercely defending its territory.',
    type: 'marine',
    rarity: 'uncommon',
    biomes: ['kelp_forest', 'water'],
    subregions: ['Santa Catalina Island', 'La Jolla', 'Monterey'],
    stats: { hp: 30, maxHp: 30, attack: 22, defense: 25, speed: 28 },
    isFantasy: false,
    sprite: '🐠',
    color: '#f97316',
    activeTime: ['day'],
    conservationStatus: 'LC',
    isNative: true,
    moves: [
      { name: 'Territory Rush', power: 22, type: 'attack', description: 'Aggressive territorial charge' },
      { name: 'Kelp Cover', power: 0, type: 'defend', description: 'Hides in kelp fronds' },
    ],
  },
  {
    id: 'purple-sea-urchin',
    name: 'Purple Sea Urchin',
    scientificName: 'Strongylocentrotus purpuratus',
    description: 'These spiny grazers have devoured vast kelp forests along the California coast.',
    type: 'marine',
    rarity: 'common',
    biomes: ['tidepool', 'kelp_forest', 'water'],
    subregions: ['Monterey', 'Point Reyes', 'Bodega Bay'],
    stats: { hp: 35, maxHp: 35, attack: 15, defense: 45, speed: 5 },
    isFantasy: false,
    sprite: '🟣',
    color: '#7e22ce',
    activeTime: ['day', 'night'],
    conservationStatus: 'LC',
    isNative: true,
    moves: [
      { name: 'Spine Guard', power: 0, type: 'defend', description: 'Bristles with venomous spines' },
      { name: 'Spine Jab', power: 18, type: 'attack', description: 'Stabs with sharp spines' },
    ],
  },
  {
    id: 'yosemite-toad',
    name: 'Yosemite Toad',
    scientificName: 'Anaxyrus canorus',
    description: 'Found only in the high Sierra meadows, one of the rarest toads in the world.',
    type: 'amphibian',
    rarity: 'rare',
    biomes: ['alpine', 'grassland'],
    subregions: ['Yosemite', 'Mammoth Lakes'],
    stats: { hp: 30, maxHp: 30, attack: 20, defense: 28, speed: 18 },
    isFantasy: false,
    sprite: '🐸',
    color: '#65a30d',
    activeTime: ['day'],
    conservationStatus: 'EN',
    isNative: true,
    isEndemic: true,
    moves: [
      { name: 'Meadow Song', power: 18, type: 'special', description: 'Melodic trill confuses foe' },
      { name: 'Mud Splash', power: 20, type: 'attack', description: 'Flings alpine mud' },
      { name: 'Snow Melt Hide', power: 0, type: 'defend', description: 'Burrows under snowmelt' },
    ],
  },
  {
    id: 'manzanita-sprite',
    name: 'Manzanita Sprite',
    scientificName: 'Spiritus arctostaphylos',
    description: 'A mischievous spirit born from the twisted red bark of ancient manzanita groves.',
    type: 'mystic',
    rarity: 'rare',
    biomes: ['chaparral', 'scrubland'],
    subregions: ['Mt. Diablo', 'Pinnacles', 'Big Sur'],
    stats: { hp: 35, maxHp: 35, attack: 32, defense: 20, speed: 38 },
    isFantasy: true,
    sprite: '🌺',
    color: '#dc2626',
    activeTime: ['dusk', 'night'],
    moves: [
      { name: 'Bark Peel', power: 25, type: 'attack', description: 'Lashes with curling red bark' },
      { name: 'Berry Hex', power: 28, type: 'special', description: 'Toxic manzanita berry curse' },
      { name: 'Root Tangle', power: 0, type: 'defend', description: 'Roots snare attacker' },
    ],
  },
  {
    id: 'sequoia-guardian',
    name: 'Sequoia Guardian',
    scientificName: 'Custos sequoiadendron',
    description: 'An ancient tree spirit that protects the oldest living things on Earth.',
    type: 'mystic',
    rarity: 'legendary',
    biomes: ['redwood', 'forest'],
    subregions: ['Sequoia', 'Kings Canyon', 'Muir Woods'],
    stats: { hp: 80, maxHp: 80, attack: 30, defense: 50, speed: 8 },
    isFantasy: true,
    sprite: '🌲',
    color: '#166534',
    activeTime: ['dawn', 'dusk'],
    moves: [
      { name: 'Ancient Growth', power: 0, type: 'defend', description: 'Heals with millennia of stored energy' },
      { name: 'Timber Fall', power: 35, type: 'attack', description: 'Drops a massive branch' },
      { name: 'Ring of Ages', power: 30, type: 'special', description: 'Power of 3000 growth rings' },
    ],
  },
  {
    id: 'mojave-phantom',
    name: 'Mojave Phantom',
    scientificName: 'Spectrum deserti',
    description: 'A shimmering mirage spirit that dances above the scorching desert floor.',
    type: 'mystic',
    rarity: 'rare',
    biomes: ['desert', 'dunes'],
    subregions: ['Death Valley', 'Mojave Desert', 'Joshua Tree'],
    stats: { hp: 30, maxHp: 30, attack: 35, defense: 15, speed: 42 },
    isFantasy: true,
    sprite: '👻',
    color: '#fbbf24',
    activeTime: ['day'],
    activeWeather: ['sunny', 'clear'],
    moves: [
      { name: 'Heat Mirage', power: 28, type: 'special', description: 'Illusion distorts reality' },
      { name: 'Sand Vortex', power: 30, type: 'attack', description: 'Whirling column of hot sand' },
      { name: 'Fade', power: 0, type: 'defend', description: 'Becomes transparent' },
    ],
  },
  {
    id: 'kelp-wraith',
    name: 'Kelp Wraith',
    scientificName: 'Phantasma macrocystis',
    description: 'A ghostly entity tangled in giant kelp, dragging prey into the deep.',
    type: 'mystic',
    rarity: 'rare',
    biomes: ['kelp_forest', 'water'],
    subregions: ['Monterey', 'Point Lobos', 'La Jolla'],
    stats: { hp: 45, maxHp: 45, attack: 32, defense: 28, speed: 25 },
    isFantasy: true,
    sprite: '🌊',
    color: '#065f46',
    activeTime: ['night', 'dusk'],
    activeWeather: ['fog'],
    moves: [
      { name: 'Kelp Snare', power: 25, type: 'attack', description: 'Tendrils drag prey down' },
      { name: 'Depth Pressure', power: 28, type: 'special', description: 'Crushing ocean pressure wave' },
      { name: 'Tidal Cloak', power: 0, type: 'defend', description: 'Wraps in swirling kelp' },
    ],
  },
  {
    id: 'coast-horned-lizard',
    name: 'Coast Horned Lizard',
    scientificName: 'Phrynosoma blainvillii',
    description: 'This spiny lizard has a horrifying defense — it shoots blood from its eyes.',
    type: 'reptile',
    rarity: 'uncommon',
    biomes: ['chaparral', 'scrubland', 'grassland'],
    subregions: ['San Diego', 'Riverside', 'Santa Barbara'],
    stats: { hp: 30, maxHp: 30, attack: 20, defense: 35, speed: 15 },
    isFantasy: false,
    sprite: '🦎',
    color: '#b45309',
    activeTime: ['day'],
    conservationStatus: 'LC',
    isNative: true,
    moves: [
      { name: 'Blood Squirt', power: 22, type: 'special', description: 'Shoots blood from eyes' },
      { name: 'Spike Puff', power: 0, type: 'defend', description: 'Inflates to show spines' },
    ],
  },
  {
    id: 'california-poppy-sprite',
    name: 'Poppy Sprite',
    scientificName: 'Fata eschscholzia',
    description: 'A tiny golden spirit that blooms with California\'s state flower in spring.',
    type: 'plant',
    rarity: 'uncommon',
    biomes: ['grassland', 'chaparral', 'valley'],
    subregions: ['Antelope Valley', 'Marin Headlands', 'Mt. Diablo'],
    stats: { hp: 28, maxHp: 28, attack: 22, defense: 20, speed: 30 },
    isFantasy: true,
    sprite: '🌼',
    color: '#f59e0b',
    activeTime: ['day'],
    activeWeather: ['sunny', 'clear'],
    moves: [
      { name: 'Pollen Burst', power: 20, type: 'special', description: 'Cloud of golden pollen' },
      { name: 'Petal Blade', power: 22, type: 'attack', description: 'Razor-sharp petals slice' },
    ],
  },
  {
    id: 'desert-iguana',
    name: 'Desert Iguana',
    scientificName: 'Dipsosaurus dorsalis',
    description: 'Thrives in temperatures that would kill most reptiles — active at 115°F.',
    type: 'reptile',
    rarity: 'common',
    biomes: ['desert', 'dunes'],
    subregions: ['Death Valley', 'Anza-Borrego', 'Mojave Desert'],
    stats: { hp: 30, maxHp: 30, attack: 20, defense: 22, speed: 32 },
    isFantasy: false,
    sprite: '🦎',
    color: '#d4a574',
    activeTime: ['day'],
    conservationStatus: 'LC',
    isNative: true,
    moves: [
      { name: 'Heat Rush', power: 20, type: 'attack', description: 'Charges with heat-fueled energy' },
      { name: 'Sand Burial', power: 0, type: 'defend', description: 'Dives beneath hot sand' },
    ],
  },
  {
    id: 'sierra-glow',
    name: 'Sierra Glow',
    scientificName: 'Lumen montanum',
    description: 'A bioluminescent alpine spirit that illuminates high Sierra lakes at night.',
    type: 'mystic',
    rarity: 'legendary',
    biomes: ['alpine', 'mountain'],
    subregions: ['Lake Tahoe', 'Yosemite', 'Mt. Whitney'],
    stats: { hp: 50, maxHp: 50, attack: 38, defense: 25, speed: 35 },
    isFantasy: true,
    sprite: '✨',
    color: '#38bdf8',
    activeTime: ['night'],
    moves: [
      { name: 'Starlight Beam', power: 35, type: 'special', description: 'Concentrated moonlight blast' },
      { name: 'Aurora Wave', power: 30, type: 'attack', description: 'Rippling curtain of light' },
      { name: 'Glacier Shield', power: 0, type: 'defend', description: 'Wall of crystallized light' },
    ],
  },
]
